"use strict";this.default_windowbootstrap=this.default_windowbootstrap||{};(function(_){var window=this;
try{
/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var aa,ba,ca,da,ea,fa,ia;aa=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};ba="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
ca=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("a");};da=ca(this);ea=function(a,b){if(b)a:{var c=da;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&ba(c,a,{configurable:!0,writable:!0,value:b})}};
ea("Symbol",function(a){if(a)return a;var b=function(g,h){this.g=g;ba(this,"description",{configurable:!0,writable:!0,value:h})};b.prototype.toString=function(){return this.g};var c="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",d=0,e=function(g){if(this instanceof e)throw new TypeError("b");return new b(c+(g||"")+"_"+d++,g)};return e});
ea("Symbol.iterator",function(a){if(a)return a;a=Symbol("c");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=da[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&ba(d.prototype,a,{configurable:!0,writable:!0,value:function(){return fa(aa(this))}})}return a});fa=function(a){a={next:a};a[Symbol.iterator]=function(){return this};return a};
_.n=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:aa(a)}};_.ha="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b};if("function"==typeof Object.setPrototypeOf)ia=Object.setPrototypeOf;else{var ja;a:{var ka={a:!0},la={};try{la.__proto__=ka;ja=la.a;break a}catch(a){}ja=!1}ia=ja?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError("d`"+a);return a}:null}_.ma=ia;
ea("Promise",function(a){function b(){this.g=null}function c(h){return h instanceof e?h:new e(function(k){k(h)})}if(a)return a;b.prototype.h=function(h){if(null==this.g){this.g=[];var k=this;this.j(function(){k.m()})}this.g.push(h)};var d=da.setTimeout;b.prototype.j=function(h){d(h,0)};b.prototype.m=function(){for(;this.g&&this.g.length;){var h=this.g;this.g=[];for(var k=0;k<h.length;++k){var l=h[k];h[k]=null;try{l()}catch(m){this.l(m)}}}this.g=null};b.prototype.l=function(h){this.j(function(){throw h;
})};var e=function(h){this.g=0;this.j=void 0;this.h=[];this.o=!1;var k=this.l();try{h(k.resolve,k.reject)}catch(l){k.reject(l)}};e.prototype.l=function(){function h(m){return function(u){l||(l=!0,m.call(k,u))}}var k=this,l=!1;return{resolve:h(this.D),reject:h(this.m)}};e.prototype.D=function(h){if(h===this)this.m(new TypeError("g"));else if(h instanceof e)this.H(h);else{a:switch(typeof h){case "object":var k=null!=h;break a;case "function":k=!0;break a;default:k=!1}k?this.K(h):this.G(h)}};e.prototype.K=
function(h){var k=void 0;try{k=h.then}catch(l){this.m(l);return}"function"==typeof k?this.M(k,h):this.G(h)};e.prototype.m=function(h){this.v(2,h)};e.prototype.G=function(h){this.v(1,h)};e.prototype.v=function(h,k){if(0!=this.g)throw Error("h`"+h+"`"+k+"`"+this.g);this.g=h;this.j=k;2===this.g&&this.U();this.A()};e.prototype.U=function(){var h=this;d(function(){if(h.ha()){var k=da.console;"undefined"!==typeof k&&k.error(h.j)}},1)};e.prototype.ha=function(){if(this.o)return!1;var h=da.CustomEvent,k=
da.Event,l=da.dispatchEvent;if("undefined"===typeof l)return!0;"function"===typeof h?h=new h("unhandledrejection",{cancelable:!0}):"function"===typeof k?h=new k("unhandledrejection",{cancelable:!0}):(h=da.document.createEvent("CustomEvent"),h.initCustomEvent("unhandledrejection",!1,!0,h));h.promise=this;h.reason=this.j;return l(h)};e.prototype.A=function(){if(null!=this.h){for(var h=0;h<this.h.length;++h)g.h(this.h[h]);this.h=null}};var g=new b;e.prototype.H=function(h){var k=this.l();h.Zb(k.resolve,
k.reject)};e.prototype.M=function(h,k){var l=this.l();try{h.call(k,l.resolve,l.reject)}catch(m){l.reject(m)}};e.prototype.then=function(h,k){function l(C,w){return"function"==typeof C?function(G){try{m(C(G))}catch(T){u(T)}}:w}var m,u,y=new e(function(C,w){m=C;u=w});this.Zb(l(h,m),l(k,u));return y};e.prototype.catch=function(h){return this.then(void 0,h)};e.prototype.Zb=function(h,k){function l(){switch(m.g){case 1:h(m.j);break;case 2:k(m.j);break;default:throw Error("i`"+m.g);}}var m=this;null==this.h?
g.h(l):this.h.push(l);this.o=!0};e.resolve=c;e.reject=function(h){return new e(function(k,l){l(h)})};e.race=function(h){return new e(function(k,l){for(var m=_.n(h),u=m.next();!u.done;u=m.next())c(u.value).Zb(k,l)})};e.all=function(h){var k=_.n(h),l=k.next();return l.done?c([]):new e(function(m,u){function y(G){return function(T){C[G]=T;w--;0==w&&m(C)}}var C=[],w=0;do C.push(void 0),w++,c(l.value).Zb(y(C.length-1),u),l=k.next();while(!l.done)})};return e});
var na=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
ea("WeakMap",function(a){function b(){}function c(l){var m=typeof l;return"object"===m&&null!==l||"function"===m}function d(l){if(!na(l,g)){var m=new b;ba(l,g,{value:m})}}function e(l){var m=Object[l];m&&(Object[l]=function(u){if(u instanceof b)return u;Object.isExtensible(u)&&d(u);return m(u)})}if(function(){if(!a||!Object.seal)return!1;try{var l=Object.seal({}),m=Object.seal({}),u=new a([[l,2],[m,3]]);if(2!=u.get(l)||3!=u.get(m))return!1;u.delete(l);u.set(m,4);return!u.has(l)&&4==u.get(m)}catch(y){return!1}}())return a;
var g="$jscomp_hidden_"+Math.random();e("freeze");e("preventExtensions");e("seal");var h=0,k=function(l){this.g=(h+=Math.random()+1).toString();if(l){l=_.n(l);for(var m;!(m=l.next()).done;)m=m.value,this.set(m[0],m[1])}};k.prototype.set=function(l,m){if(!c(l))throw Error("j");d(l);if(!na(l,g))throw Error("k`"+l);l[g][this.g]=m;return this};k.prototype.get=function(l){return c(l)&&na(l,g)?l[g][this.g]:void 0};k.prototype.has=function(l){return c(l)&&na(l,g)&&na(l[g],this.g)};k.prototype.delete=function(l){return c(l)&&
na(l,g)&&na(l[g],this.g)?delete l[g][this.g]:!1};return k});
ea("Map",function(a){if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var k=Object.seal({x:4}),l=new a(_.n([[k,"s"]]));if("s"!=l.get(k)||1!=l.size||l.get({x:4})||l.set({x:4},"t")!=l||2!=l.size)return!1;var m=l.entries(),u=m.next();if(u.done||u.value[0]!=k||"s"!=u.value[1])return!1;u=m.next();return u.done||4!=u.value[0].x||"t"!=u.value[1]||!m.next().done?!1:!0}catch(y){return!1}}())return a;var b=new WeakMap,c=function(k){this.h={};this.g=
g();this.size=0;if(k){k=_.n(k);for(var l;!(l=k.next()).done;)l=l.value,this.set(l[0],l[1])}};c.prototype.set=function(k,l){k=0===k?0:k;var m=d(this,k);m.list||(m.list=this.h[m.id]=[]);m.entry?m.entry.value=l:(m.entry={next:this.g,previous:this.g.previous,head:this.g,key:k,value:l},m.list.push(m.entry),this.g.previous.next=m.entry,this.g.previous=m.entry,this.size++);return this};c.prototype.delete=function(k){k=d(this,k);return k.entry&&k.list?(k.list.splice(k.index,1),k.list.length||delete this.h[k.id],
k.entry.previous.next=k.entry.next,k.entry.next.previous=k.entry.previous,k.entry.head=null,this.size--,!0):!1};c.prototype.clear=function(){this.h={};this.g=this.g.previous=g();this.size=0};c.prototype.has=function(k){return!!d(this,k).entry};c.prototype.get=function(k){return(k=d(this,k).entry)&&k.value};c.prototype.entries=function(){return e(this,function(k){return[k.key,k.value]})};c.prototype.keys=function(){return e(this,function(k){return k.key})};c.prototype.values=function(){return e(this,
function(k){return k.value})};c.prototype.forEach=function(k,l){for(var m=this.entries(),u;!(u=m.next()).done;)u=u.value,k.call(l,u[1],u[0],this)};c.prototype[Symbol.iterator]=c.prototype.entries;var d=function(k,l){var m=l&&typeof l;"object"==m||"function"==m?b.has(l)?m=b.get(l):(m=""+ ++h,b.set(l,m)):m="p_"+l;var u=k.h[m];if(u&&na(k.h,m))for(k=0;k<u.length;k++){var y=u[k];if(l!==l&&y.key!==y.key||l===y.key)return{id:m,list:u,index:k,entry:y}}return{id:m,list:u,index:-1,entry:void 0}},e=function(k,
l){var m=k.g;return fa(function(){if(m){for(;m.head!=k.g;)m=m.previous;for(;m.next!=m.head;)return m=m.next,{done:!1,value:l(m)};m=null}return{done:!0,value:void 0}})},g=function(){var k={};return k.previous=k.next=k.head=k},h=0;return c});ea("Array.prototype.find",function(a){return a?a:function(b,c){a:{var d=this;d instanceof String&&(d=String(d));for(var e=d.length,g=0;g<e;g++){var h=d[g];if(b.call(c,h,g,d)){b=h;break a}}b=void 0}return b}});
var oa=function(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var g=c++;return{value:b(g,a[g]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e};ea("Array.prototype.entries",function(a){return a?a:function(){return oa(this,function(b,c){return[b,c]})}});ea("Array.prototype.keys",function(a){return a?a:function(){return oa(this,function(b){return b})}});
ea("Array.from",function(a){return a?a:function(b,c,d){c=null!=c?c:function(k){return k};var e=[],g="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];if("function"==typeof g){b=g.call(b);for(var h=0;!(g=b.next()).done;)e.push(c.call(d,g.value,h++))}else for(g=b.length,h=0;h<g;h++)e.push(c.call(d,b[h],h));return e}});ea("Array.prototype.values",function(a){return a?a:function(){return oa(this,function(b,c){return c})}});
var pa="function"==typeof Object.assign?Object.assign:function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c];if(d)for(var e in d)na(d,e)&&(a[e]=d[e])}return a};ea("Object.assign",function(a){return a||pa});ea("Object.entries",function(a){return a?a:function(b){var c=[],d;for(d in b)na(b,d)&&c.push([d,b[d]]);return c}});ea("Object.is",function(a){return a?a:function(b,c){return b===c?0!==b||1/b===1/c:b!==b&&c!==c}});
ea("Array.prototype.includes",function(a){return a?a:function(b,c){var d=this;d instanceof String&&(d=String(d));var e=d.length;c=c||0;for(0>c&&(c=Math.max(c+e,0));c<e;c++){var g=d[c];if(g===b||Object.is(g,b))return!0}return!1}});ea("String.prototype.includes",function(a){return a?a:function(b,c){if(null==this)throw new TypeError("l`includes");if(b instanceof RegExp)throw new TypeError("m`includes");return-1!==this.indexOf(b,c||0)}});
ea("Set",function(a){if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var c=Object.seal({x:4}),d=new a(_.n([c]));if(!d.has(c)||1!=d.size||d.add(c)!=d||1!=d.size||d.add({x:4})!=d||2!=d.size)return!1;var e=d.entries(),g=e.next();if(g.done||g.value[0]!=c||g.value[1]!=c)return!1;g=e.next();return g.done||g.value[0]==c||4!=g.value[0].x||g.value[1]!=g.value[0]?!1:e.next().done}catch(h){return!1}}())return a;var b=function(c){this.g=new Map;if(c){c=
_.n(c);for(var d;!(d=c.next()).done;)this.add(d.value)}this.size=this.g.size};b.prototype.add=function(c){c=0===c?0:c;this.g.set(c,c);this.size=this.g.size;return this};b.prototype.delete=function(c){c=this.g.delete(c);this.size=this.g.size;return c};b.prototype.clear=function(){this.g.clear();this.size=0};b.prototype.has=function(c){return this.g.has(c)};b.prototype.entries=function(){return this.g.entries()};b.prototype.values=function(){return this.g.values()};b.prototype.keys=b.prototype.values;
b.prototype[Symbol.iterator]=b.prototype.values;b.prototype.forEach=function(c,d){var e=this;this.g.forEach(function(g){return c.call(d,g,g,e)})};return b});_.qa=_.qa||{};_.p=this||self;_.ra="closure_uid_"+(1E9*Math.random()>>>0);

}catch(e){_._DumpException(e)}
try{
_.Hg="https://support.google.com/chrome/answer/185277?hl="+chrome.i18n.getMessage("@@ui_locale");chrome.i18n.getMessage("@@ui_locale");_.Ig="https://support.google.com/hangouts/answer/6127720?hl="+chrome.i18n.getMessage("@@ui_locale");

}catch(e){_._DumpException(e)}
try{
location.search&&window.addEventListener("load",function(){chrome.runtime.getBackgroundPage(function(a){a.__onExtWindowLoad(window)})});

}catch(e){_._DumpException(e)}
}).call(this,this.default_windowbootstrap);
// Google Inc.
