/* Copyright 2014 Google */ (function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var k=this||self,m=function(){},n=function(a){var b=typeof a;return"object"!=b?b:a?Array.isArray(a)?"array":b:"null"},aa=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b},ba=function(a,b,c){return a.call.apply(a.bind,arguments)},ca=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var e=Array.prototype.slice.call(arguments,2);return function(){var d=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(d,e);return a.apply(b,d)}}return function(){return a.apply(b,
arguments)}},p=function(a,b,c){Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?p=ba:p=ca;return p.apply(null,arguments)},q=function(a,b){function c(){}c.prototype=b.prototype;a.O=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.N=function(e,d,f){for(var g=Array(arguments.length-2),h=2;h<arguments.length;h++)g[h-2]=arguments[h];return b.prototype[d].apply(e,g)}},r=function(a){return a};function t(a,b){return a.replace(/\{\{\$.*?\}\}/g,function(c){c=c.substr(3,c.length-5);return String(b[c])||""})}function u(a){a=String(a).toLowerCase().replace("_","-");if("zh-cn"==a)return"zh-CN";if("zh-tw"==a)return"zh-TW";var b=a.indexOf("-");a=0<=b?a.substring(0,b):a;return"zh"==a?"zh-CN":a};function v(a){if(Error.captureStackTrace)Error.captureStackTrace(this,v);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))}q(v,Error);v.prototype.name="CustomError";var w=function(a,b){a=a.split("%s");for(var c="",e=a.length-1,d=0;d<e;d++)c+=a[d]+(d<b.length?b[d]:"%s");v.call(this,c+a[e])};q(w,v);w.prototype.name="AssertionError";
var da=function(a,b,c,e){var d="Assertion failed";if(c){d+=": "+c;var f=e}else a&&(d+=": "+a,f=b);throw new w(""+d,f||[]);},x=function(a,b,c){a||da("",null,b,Array.prototype.slice.call(arguments,2));return a},y=function(a,b){throw new w("Failure"+(a?": "+a:""),Array.prototype.slice.call(arguments,1));},z=function(a,b,c){"function"!==typeof a&&da("Expected function but got %s: %s.",[n(a),a],b,Array.prototype.slice.call(arguments,2))};var A;var B=function(a,b){this.g=a===ea&&b||"";this.h=fa};B.prototype.B=!0;B.prototype.v=function(){return this.g};B.prototype.toString=function(){return"Const{"+this.g+"}"};var fa={},ea={};var C=function(a,b){this.g=b===ha?a:""};C.prototype.B=!0;C.prototype.v=function(){return this.g.toString()};C.prototype.toString=function(){return this.g+""};
var D=function(a){if(a instanceof C&&a.constructor===C)return a.g;y("expected object of type TrustedResourceUrl, got '"+a+"' of type "+n(a));return"type_error:TrustedResourceUrl"},ia=/^([^?#]*)(\?[^#]*)?(#[\s\S]*)?/,ha={},ja=function(a){if(void 0===A){var b=null;var c=k.trustedTypes;if(c&&c.createPolicy){try{b=c.createPolicy("goog#html",{createHTML:r,createScript:r,createScriptURL:r})}catch(e){k.console&&k.console.error(e.message)}A=b}else A=b}a=(b=A)?b.createScriptURL(a):a;return new C(a,ha)},ka=
function(a,b,c){if(null==c)return b;if("string"===typeof c)return c?a+encodeURIComponent(c):"";for(var e in c)if(Object.prototype.hasOwnProperty.call(c,e)){var d=c[e];d=Array.isArray(d)?d:[d];for(var f=0;f<d.length;f++){var g=d[f];null!=g&&(b||(b=a),b+=(b.length>a.length?"&":"")+encodeURIComponent(e)+"="+encodeURIComponent(String(g)))}}return b};var la=Array.prototype.some?function(a,b){x(null!=a.length);return Array.prototype.some.call(a,b,void 0)}:function(a,b){for(var c=a.length,e="string"===typeof a?a.split(""):a,d=0;d<c;d++)if(d in e&&b.call(void 0,e[d],d,a))return!0;return!1};var E;a:{var ma=k.navigator;if(ma){var na=ma.userAgent;if(na){E=na;break a}}E=""}var F=function(a){return-1!=E.indexOf(a)};function oa(a,b){for(var c in a)b.call(void 0,a[c],c,a)}var qa="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function ra(a,b){for(var c,e,d=1;d<arguments.length;d++){e=arguments[d];for(c in e)a[c]=e[c];for(var f=0;f<qa.length;f++)c=qa[f],Object.prototype.hasOwnProperty.call(e,c)&&(a[c]=e[c])}};var sa=function(a,b){a:{try{var c=a&&a.ownerDocument,e=c&&(c.defaultView||c.parentWindow);e=e||k;if(e.Element&&e.Location){var d=e;break a}}catch(g){}d=null}if(d&&"undefined"!=typeof d[b]&&(!a||!(a instanceof d[b])&&(a instanceof d.Location||a instanceof d.Element))){if(aa(a))try{var f=a.constructor.displayName||a.constructor.name||Object.prototype.toString.call(a)}catch(g){f="<object could not be stringified>"}else f=void 0===a?"undefined":null===a?"null":typeof a;y("Argument is not a %s (or a non-Element, non-Location mock); got: %s",
b,f)}};var H=function(a,b){this.g=b===G?a:""};H.prototype.B=!0;H.prototype.v=function(){return this.g.toString()};H.prototype.toString=function(){return this.g.toString()};
var ta=/^(?:audio\/(?:3gpp2|3gpp|aac|L16|midi|mp3|mp4|mpeg|oga|ogg|opus|x-m4a|x-matroska|x-wav|wav|webm)|font\/\w+|image\/(?:bmp|gif|jpeg|jpg|png|tiff|webp|x-icon)|video\/(?:mpeg|mp4|ogg|webm|quicktime|x-matroska))(?:;\w+=(?:\w+|"[\w;,= ]+"))*$/i,ua=/^data:(.*);base64,[a-z0-9+\/]+=*$/i,va=/^(?:(?:https?|mailto|ftp):|[^:/?#]*(?:[/?#]|$))/i,G={},wa=new H("about:invalid#zClosurez",G);var xa=function(a){var b=I;sa(b,"HTMLAudioElement");if(a instanceof H)var c=a;else a:if(c=a,a=/^data:audio\//i.test(a),!(c instanceof H)){c="object"==typeof c&&c.B?c.v():String(c);if(a&&/^data:/i.test(c)){a=String(c);a=a.replace(/(%0A|%0D)/g,"");var e=a.match(ua);a=(e&&ta.test(e[1])?new H(a,G):null)||wa;if(a.v()==c){c=a;break a}}x(va.test(c),"%s does not match the safe URL pattern",c)||(c="about:invalid#zClosurez");c=new H(c,G)}c instanceof H&&c.constructor===H?c=c.g:(y("expected object of type SafeUrl, got '"+
c+"' of type "+n(c)),c="type_error:SafeUrl");b.src=c},za=function(a,b){sa(a,"HTMLScriptElement");a.src=D(b);a:{b=(a.ownerDocument&&a.ownerDocument.defaultView||k).document;if(b.querySelector&&(b=b.querySelector("script[nonce]"))&&(b=b.nonce||b.getAttribute("nonce"))&&ya.test(b))break a;b=""}b&&a.setAttribute("nonce",b)},ya=/^[\w+/_-]+[=]{0,2}$/;var Aa=F("Opera"),J=F("Trident")||F("MSIE"),Ba=F("Edge"),K=F("Gecko")&&!(-1!=E.toLowerCase().indexOf("webkit")&&!F("Edge"))&&!(F("Trident")||F("MSIE"))&&!F("Edge"),Ca=-1!=E.toLowerCase().indexOf("webkit")&&!F("Edge"),Da=function(){var a=k.document;return a?a.documentMode:void 0},L;
a:{var Ea="",Fa=function(){var a=E;if(K)return/rv:([^\);]+)(\)|;)/.exec(a);if(Ba)return/Edge\/([\d\.]+)/.exec(a);if(J)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(Ca)return/WebKit\/(\S+)/.exec(a);if(Aa)return/(?:Version)[ \/]?(\S+)/.exec(a)}();Fa&&(Ea=Fa?Fa[1]:"");if(J){var Ga=Da();if(null!=Ga&&Ga>parseFloat(Ea)){L=String(Ga);break a}}L=Ea}var Ha=L,Ia;if(k.document&&J){var Ja=Da();Ia=Ja?Ja:parseInt(Ha,10)||void 0}else Ia=void 0;var Ka=Ia;var La;if(!(La=!K&&!J)){var Ma;if(Ma=J)Ma=9<=Number(Ka);La=Ma}var Na=La||K;var Pa=function(a,b){oa(b,function(c,e){c&&"object"==typeof c&&c.B&&(c=c.v());"style"==e?a.style.cssText=c:"class"==e?a.className=c:"for"==e?a.htmlFor=c:Oa.hasOwnProperty(e)?a.setAttribute(Oa[e],c):0==e.lastIndexOf("aria-",0)||0==e.lastIndexOf("data-",0)?a.setAttribute(e,c):a[e]=c})},Oa={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",
width:"width"},Qa=function(a,b){b=String(b);"application/xhtml+xml"===a.contentType&&(b=b.toLowerCase());return a.createElement(b)},Ra=function(a){this.g=a||k.document||document};Ra.prototype.getChildren=function(a){return Na&&void 0!=a.children?a.children:Array.prototype.filter.call(a.childNodes,function(b){return 1==b.nodeType})};
Ra.prototype.contains=function(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a};var Sa=function(a,b){this.i=a;this.j=b;this.h=0;this.g=null};Sa.prototype.get=function(){if(0<this.h){this.h--;var a=this.g;this.g=a.next;a.next=null}else a=this.i();return a};var Ta=function(a,b){a.j(b);100>a.h&&(a.h++,b.next=a.g,a.g=b)};var Ua,Va=function(){var a=k.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&!F("Presto")&&(a=function(){var d=Qa(document,"IFRAME");d.style.display="none";document.documentElement.appendChild(d);var f=d.contentWindow;d=f.document;d.open();d.close();var g="callImmediate"+Math.random(),h="file:"==f.location.protocol?"*":f.location.protocol+"//"+f.location.host;d=p(function(l){if(("*"==h||l.origin==h)&&l.data==g)this.port1.onmessage()},
this);f.addEventListener("message",d,!1);this.port1={};this.port2={postMessage:function(){f.postMessage(g,h)}}});if("undefined"!==typeof a&&!F("Trident")&&!F("MSIE")){var b=new a,c={},e=c;b.port1.onmessage=function(){if(void 0!==c.next){c=c.next;var d=c.J;c.J=null;d()}};return function(d){e.next={J:d};e=e.next;b.port2.postMessage(0)}}return function(d){k.setTimeout(d,0)}};function Wa(a){k.setTimeout(function(){throw a;},0)};var Xa=function(){this.h=this.g=null};Xa.prototype.add=function(a,b){var c=Ya.get();c.set(a,b);this.h?this.h.next=c:(x(!this.g),this.g=c);this.h=c};Xa.prototype.remove=function(){var a=null;this.g&&(a=this.g,this.g=this.g.next,this.g||(this.h=null),a.next=null);return a};var Ya=new Sa(function(){return new Za},function(a){return a.reset()}),Za=function(){this.next=this.g=this.h=null};Za.prototype.set=function(a,b){this.h=a;this.g=b;this.next=null};
Za.prototype.reset=function(){this.next=this.g=this.h=null};var cb=function(a,b){M||$a();ab||(M(),ab=!0);bb.add(a,b)},M,$a=function(){if(k.Promise&&k.Promise.resolve){var a=k.Promise.resolve(void 0);M=function(){a.then(db)}}else M=function(){var b=db;"function"!==typeof k.setImmediate||k.Window&&k.Window.prototype&&!F("Edge")&&k.Window.prototype.setImmediate==k.setImmediate?(Ua||(Ua=Va()),Ua(b)):k.setImmediate(b)}},ab=!1,bb=new Xa,db=function(){for(var a;a=bb.remove();){try{a.h.call(a.g)}catch(b){Wa(b)}Ta(Ya,a)}ab=!1};var eb=function(a){if(!a)return!1;try{return!!a.$goog_Thenable}catch(b){return!1}};var P=function(a){this.g=0;this.s=void 0;this.j=this.h=this.i=null;this.l=this.m=!1;if(a!=m)try{var b=this;a.call(void 0,function(c){N(b,2,c)},function(c){if(!(c instanceof O))try{if(c instanceof Error)throw c;throw Error("Promise rejected.");}catch(e){}N(b,3,c)})}catch(c){N(this,3,c)}},fb=function(){this.next=this.j=this.i=this.h=this.g=null;this.l=!1};fb.prototype.reset=function(){this.j=this.i=this.h=this.g=null;this.l=!1};
var gb=new Sa(function(){return new fb},function(a){a.reset()}),hb=function(a,b,c){var e=gb.get();e.h=a;e.i=b;e.j=c;return e};P.prototype.then=function(a,b,c){null!=a&&z(a,"opt_onFulfilled should be a function.");null!=b&&z(b,"opt_onRejected should be a function. Did you pass opt_context as the second argument instead of the third?");return ib(this,"function"===typeof a?a:null,"function"===typeof b?b:null,c)};P.prototype.$goog_Thenable=!0;
P.prototype.cancel=function(a){if(0==this.g){var b=new O(a);cb(function(){jb(this,b)},this)}};
var jb=function(a,b){if(0==a.g)if(a.i){var c=a.i;if(c.h){for(var e=0,d=null,f=null,g=c.h;g&&(g.l||(e++,g.g==a&&(d=g),!(d&&1<e)));g=g.next)d||(f=g);d&&(0==c.g&&1==e?jb(c,b):(f?(e=f,x(c.h),x(null!=e),e.next==c.j&&(c.j=e),e.next=e.next.next):kb(c),lb(c,d,3,b)))}a.i=null}else N(a,3,b)},nb=function(a,b){a.h||2!=a.g&&3!=a.g||mb(a);x(null!=b.h);a.j?a.j.next=b:a.h=b;a.j=b},ib=function(a,b,c,e){var d=hb(null,null,null);d.g=new P(function(f,g){d.h=b?function(h){try{var l=b.call(e,h);f(l)}catch(pa){g(pa)}}:
f;d.i=c?function(h){try{var l=c.call(e,h);void 0===l&&h instanceof O?g(h):f(l)}catch(pa){g(pa)}}:g});d.g.i=a;nb(a,d);return d.g};P.prototype.A=function(a){x(1==this.g);this.g=0;N(this,2,a)};P.prototype.D=function(a){x(1==this.g);this.g=0;N(this,3,a)};
var N=function(a,b,c){if(0==a.g){a===c&&(b=3,c=new TypeError("Promise cannot resolve to itself"));a.g=1;a:{var e=c,d=a.A,f=a.D;if(e instanceof P){null!=d&&z(d,"opt_onFulfilled should be a function.");null!=f&&z(f,"opt_onRejected should be a function. Did you pass opt_context as the second argument instead of the third?");nb(e,hb(d||m,f||null,a));var g=!0}else if(eb(e))e.then(d,f,a),g=!0;else{if(aa(e))try{var h=e.then;if("function"===typeof h){ob(e,h,d,f,a);g=!0;break a}}catch(l){f.call(a,l);g=!0;
break a}g=!1}}g||(a.s=c,a.g=b,a.i=null,mb(a),3!=b||c instanceof O||pb(a,c))}},ob=function(a,b,c,e,d){var f=!1,g=function(l){f||(f=!0,c.call(d,l))},h=function(l){f||(f=!0,e.call(d,l))};try{b.call(a,g,h)}catch(l){h(l)}},mb=function(a){a.m||(a.m=!0,cb(a.u,a))},kb=function(a){var b=null;a.h&&(b=a.h,a.h=b.next,b.next=null);a.h||(a.j=null);null!=b&&x(null!=b.h);return b};P.prototype.u=function(){for(var a;a=kb(this);)lb(this,a,this.g,this.s);this.m=!1};
var lb=function(a,b,c,e){if(3==c&&b.i&&!b.l)for(;a&&a.l;a=a.i)a.l=!1;if(b.g)b.g.i=null,qb(b,c,e);else try{b.l?b.h.call(b.j):qb(b,c,e)}catch(d){rb.call(null,d)}Ta(gb,b)},qb=function(a,b,c){2==b?a.h.call(a.j,c):a.i&&a.i.call(a.j,c)},pb=function(a,b){a.l=!0;cb(function(){a.l&&rb.call(null,b)})},rb=Wa,O=function(a){v.call(this,a)};q(O,v);O.prototype.name="cancel";/*

 Copyright 2005, 2007 Bob Ippolito. All Rights Reserved.
 Copyright The Closure Library Authors.
 SPDX-License-Identifier: MIT
*/
var Q=function(a){var b=sb;this.l=[];this.I=b;this.H=a||null;this.j=this.i=!1;this.h=void 0;this.A=this.D=this.s=!1;this.m=0;this.g=null;this.u=0};Q.prototype.cancel=function(a){if(this.i)this.h instanceof Q&&this.h.cancel();else{if(this.g){var b=this.g;delete this.g;a?b.cancel(a):(b.u--,0>=b.u&&b.cancel())}this.I?this.I.call(this.H,this):this.A=!0;this.i||tb(this,new R(this))}};Q.prototype.G=function(a,b){this.s=!1;ub(this,a,b)};
var ub=function(a,b,c){a.i=!0;a.h=c;a.j=!b;vb(a)},wb=function(a){if(a.i){if(!a.A)throw new S(a);a.A=!1}},tb=function(a,b){wb(a);xb(b);ub(a,!1,b)},xb=function(a){x(!(a instanceof Q),"An execution sequence may not be initiated with a blocking Deferred.")},yb=function(a,b,c,e){x(!a.D,"Blocking Deferreds can not be re-used");a.l.push([b,c,e]);a.i&&vb(a)};Q.prototype.then=function(a,b,c){var e,d,f=new P(function(g,h){d=g;e=h});yb(this,d,function(g){g instanceof R?f.cancel():e(g)});return f.then(a,b,c)};
Q.prototype.$goog_Thenable=!0;Q.prototype.isError=function(a){return a instanceof Error};
var zb=function(a){return la(a.l,function(b){return"function"===typeof b[1]})},vb=function(a){if(a.m&&a.i&&zb(a)){var b=a.m,c=T[b];c&&(k.clearTimeout(c.o),delete T[b]);a.m=0}a.g&&(a.g.u--,delete a.g);b=a.h;for(var e=c=!1;a.l.length&&!a.s;){var d=a.l.shift(),f=d[0],g=d[1];d=d[2];if(f=a.j?g:f)try{var h=f.call(d||a.H,b);void 0!==h&&(a.j=a.j&&(h==b||a.isError(h)),a.h=b=h);if(eb(b)||"function"===typeof k.Promise&&b instanceof k.Promise)e=!0,a.s=!0}catch(l){b=l,a.j=!0,zb(a)||(c=!0)}}a.h=b;e&&(h=p(a.G,a,
!0),e=p(a.G,a,!1),b instanceof Q?(yb(b,h,e),b.D=!0):b.then(h,e));c&&(b=new Ab(b),T[b.o]=b,a.m=b.o)},S=function(){v.call(this)};q(S,v);S.prototype.message="Deferred has already fired";S.prototype.name="AlreadyCalledError";var R=function(){v.call(this)};q(R,v);R.prototype.message="Deferred was canceled";R.prototype.name="CanceledError";var Ab=function(a){this.o=k.setTimeout(p(this.h,this),0);this.g=a};
Ab.prototype.h=function(){x(T[this.o],"Cannot throw an error that is not scheduled.");delete T[this.o];throw this.g;};var T={};var Db=function(a,b){var c=b||{};b=c.document||document;var e=D(a).toString(),d=Qa((new Ra(b)).g,"SCRIPT"),f={L:d,C:void 0},g=new Q(f),h=null,l=null!=c.timeout?c.timeout:5E3;0<l&&(h=window.setTimeout(function(){U(d,!0);tb(g,new Bb(1,"Timeout reached for loading script "+e))},l),f.C=h);d.onload=d.onreadystatechange=function(){d.readyState&&"loaded"!=d.readyState&&"complete"!=d.readyState||(U(d,c.M||!1,h),wb(g),xb(null),ub(g,!0,null))};d.onerror=function(){U(d,!0,h);tb(g,new Bb(0,"Error while loading script "+
e))};f=c.attributes||{};ra(f,{type:"text/javascript",charset:"UTF-8"});Pa(d,f);za(d,a);Cb(b).appendChild(d);return g},Cb=function(a){var b;return(b=(a||document).getElementsByTagName("HEAD"))&&0!==b.length?b[0]:a.documentElement},sb=function(){if(this&&this.L){var a=this.L;a&&"SCRIPT"==a.tagName&&U(a,!0,this.C)}},U=function(a,b,c){null!=c&&k.clearTimeout(c);a.onload=m;a.onerror=m;a.onreadystatechange=m;b&&window.setTimeout(function(){a&&a.parentNode&&a.parentNode.removeChild(a)},0)},Bb=function(a,
b){var c="Jsloader error (code #"+a+")";b&&(c+=": "+b);v.call(this,c);this.code=a};q(Bb,v);var Eb=function(a){this.g=a;this.C=5E3},Fb=0;Eb.prototype.send=function(a,b,c,e){if(a){var d={};for(f in a)d[f]=a[f];a=d}else a={};e=e||"_"+(Fb++).toString(36)+Date.now().toString(36);d="_callbacks___"+e;b&&(k[d]=Gb(e,b),a.cb=d);b={timeout:this.C,M:!0};d=D(this.g).toString();d=ia.exec(d);var f=d[3]||"";d=ja(d[1]+ka("?",d[2]||"",a)+ka("#",f,void 0));b=Db(d,b);yb(b,null,Hb(e,a,c),void 0);return{o:e,K:b}};Eb.prototype.cancel=function(a){a&&(a.K&&a.K.cancel(),a.o&&Ib(a.o,!1))};
var Hb=function(a,b,c){return function(){Ib(a,!1);c&&c(b)}},Gb=function(a,b){return function(c){Ib(a,!0);b.apply(void 0,arguments)}},Ib=function(a,b){a="_callbacks___"+a;if(k[a])if(b)try{delete k[a]}catch(c){k[a]=void 0}else k[a]=m};var V=function(){this.h=[];chrome.i18n.getAcceptLanguages(p(this.m,this));this.g="";this.j="1";this.i={};chrome.storage.local.get(null,p(this.u,this));Jb(this)},Lb=function(){var a=Kb;if(""!=a.g)a=a.g;else a:{for(var b=0;b<a.h.length;b++){var c=u(a.h[b]);if(a.i[c]){a=c;break a}}a="en"}return a};
V.prototype.u=function(a){"gtxTargetLang"in a&&(this.g=a.gtxTargetLang);"gtxShowBubble"in a&&(this.j=a.gtxShowBubble);"gtxSourceLangList"in a&&Mb(this,a.gtxSourceLangList);"gtxTargetLangList"in a&&(this.i=Mb(this,a.gtxTargetLangList));this.loaded=!0;var b=(new Date).getTime(),c="gtxTimeStamp"in a?a.gtxTimeStamp:0,e=chrome.i18n.getUILanguage?chrome.i18n.getUILanguage():"en";a="gtxDisplayLanguage"in a?a.gtxDisplayLanguage:"";if(864E5<Math.abs(b-c)||e!=a)b=new B(ea,"https://translate.googleapis.com/translate_a/l"),
b instanceof B&&b.constructor===B&&b.h===fa?b=b.g:(y("expected object of type Const, got '"+b+"'"),b="type_error:Const"),b=ja(b),(new Eb(b)).send({client:"gtx",hl:e},p(this.s,this,e))};var Mb=function(a,b){var c=[],e;for(e in b)c.push({code:e,name:b[e]});c.sort(a.l);a={};for(b=0;b<c.length;b++)a[c[b].code]=c[b].name;return a};V.prototype.l=function(a,b){return a.name.localeCompare(b.name)};
var Jb=function(a){chrome.storage.onChanged.addListener(function(b){b.gtxTargetLang&&(a.g=b.gtxTargetLang.newValue);b.gtxShowBubble&&(a.j=b.gtxShowBubble.newValue)})};V.prototype.m=function(a){this.h=a};V.prototype.s=function(a,b){var c=(new Date).getTime(),e={};e.gtxSourceLangList=b.sl;e.gtxTargetLangList=b.tl;e.gtxDisplayLanguage=a;e.gtxTimeStamp=c;chrome.storage.local.set(e);this.i=b.tl};var Nb=t("(function(){({{$code}})();})();",{code:window.injection.toString()}),Ob=t("(function(){({{$code}})();})();",{code:window.injector.toString()});delete window.injector;delete window.injection;function Pb(a,b,c){b={pageLang:b,userLang:c};b.content=t(Nb,b).replace(/\\/g,"\\\\").replace(/'/g,"\\'").replace(/"/g,'\\"').replace(/\n/g,"\\n");chrome.tabs.executeScript(a,{code:t(Ob,b)},function(){chrome.runtime.lastError&&console.error(chrome.runtime.lastError.message)})}
var Qb=function(a){this.i=a;this.F=this.g=!1};Qb.prototype.popup=function(){this.g||this.F||(this.g=!0,this.h="",chrome.tabs.detectLanguage(this.i,p(this.j,this)))};Qb.prototype.j=function(a){if(!this.F){if(!a||"und"==a||a.match("invalid"))a="auto";this.h=a;a=u(Lb());var b=u(this.h);Pb(this.i,b,a);this.g=!1}};var W=function(){this.g={}};W.prototype.attach=function(a){this.g[a]||(this.g[a]=new Qb(a));this.g[a].popup()};W.prototype.detach=function(a){this.g[a]&&(this.g[a].F=!0,delete this.g[a])};
var Rb=new W,Kb=new V,I=Qa(document,"AUDIO");chrome.runtime.onMessage.addListener(function(a,b){a.audioSrc?I.paused||a.audioSrc!=I.src?(xa(a.audioSrc),I.load(),I.play()):(I.pause(),I.currentTime=0):a.bubbleClosed||a.popupClosed?I.pause():a.detectLanguage&&chrome.tabs.detectLanguage(function(c){chrome.tabs.sendMessage(b.tab.id,{"gtx.detected":c})})});chrome.runtime.onConnect.addListener(function(a){a.onDisconnect.addListener(function(){chrome.runtime.sendMessage({popupClosed:!0})})});
chrome.runtime.onInstalled.addListener(function(){var a=chrome.contextMenus,b=a.create;var c=chrome.i18n.getMessage("MSG_FOOTER_TRANSLATE");c=chrome.i18n.getMessage(c);b.call(a,{id:"translate",title:c,contexts:["selection"]})});chrome.contextMenus.onClicked.addListener(function(a){var b=chrome.tabs,c=b.create;a="https://translate.google.com/?source=gtx_c#auto/"+Lb()+"/"+encodeURIComponent(a.selectionText);c.call(b,{url:a})});var Sb=function(){return Rb},X=["translate","getTranslateManager"],Y=k;
X[0]in Y||"undefined"==typeof Y.execScript||Y.execScript("var "+X[0]);for(var Z;X.length&&(Z=X.shift());)X.length||void 0===Sb?Y[Z]&&Y[Z]!==Object.prototype[Z]?Y=Y[Z]:Y=Y[Z]={}:Y[Z]=Sb;W.prototype.attach=W.prototype.attach;W.prototype.detach=W.prototype.detach;})();
