#!/bin/sh
xrdb -load ~/.Xresources & 
xrdb ~/.Xresources & 
# sleep 1 &
# xcompmgr & 
# xterm -geometry 1600x2560+0+0 -fa SourceCodePro-Regular -fs 25 -ls -title "$VNCDESKTOP Desktop" &
urxvtd &
urxvtc &
xmonad
# /root/wtftw/target/release/wtftw
# #   xterm -geometry 1920x1080+0+0 -fa SourceCodePro-Regular -fs 25 -ls -title "$VNCDESKTOP Desktop" &
# #  xterm -maximized -fa SourceCodePro-Regular -fs 20 -ls -title "$VNCDESKTOP Desktop" 
#  &
