#!/bin/sh

unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS
# OS=`uname -s`
#  if [ $OS = 'Linux' ]; then
#   case "$WINDOWMANAGER" in
#     *gnome*)
#       if [ -e /etc/SuSE-release ]; then
#         PATH=$PATH:/opt/gnome/bin
#         export PATH
#       fi
#       ;;
#   esac
# fi
if [ -x /etc/X11/xinit/xinitrc ]; then
  exec /etc/X11/xinit/xinitrc
fi
if [ -f /etc/X11/xinit/xinitrc ]; then
  exec sh /etc/X11/xinit/xinitrc
fi
[ -r $HOME/.Xresources ] && xrdb ~/.Xresources
urxvtd -q -f -o & 
xrdb -load ~/.Xresources & 
# xcompmgr & 
xsetroot -solid grey
  # xterm -geometry 1600x2560+0+0 -fa SourceCodePro-Regular -fs 25 -ls -title "$VNCDESKTOP Desktop" &
urxvtd &
urxvtc &
xmonad 
# #   xterm -geometry 1920x1080+0+0 -fa SourceCodePro-Regular -fs 25 -ls -title "$VNCDESKTOP Desktop" &
# #  xterm -maximized -fa SourceCodePro-Regular -fs 20 -ls -title "$VNCDESKTOP Desktop" 
#  &
