#! /bin/sh

lualatex $1 $2 $3 $4 $5
echo $1 $2 $3 $4 
myfile="${5%.*}"
mypdfstring=$myfile".pdf" 
mylogstring=$myfile".log"  
sync=$myfile".synctex.gz"
if ! grep -q Fatal ./build/backup.log; then
echo cool
echo $mypdfstring
cp -r./buildback ./build 
fi
