#! /bin/sh

lualatex -halt-on-error -synctex=1 -file-line-error -jobname=backup -gg $1 $2 $3 
echo $1 $2 $3  
myfile="${3%.*}"
mypdfstring=$myfile".pdf" 
mylogstring=$myfile".log"  
sync=$myfile"synctex.gz"
if ! grep -q Fatal ./build/backup.log; then
echo cool
echo $mypdfstring
mv ./build/$mypdfstring $mypdfstring 
mv ./build/f $mypdfstring

fi
