#!/bin/sh
if [ -f $1 ]; then
nvr --nostart --servername  $(<~/servername.txt) --remote $1 
echo "trying to attach to server" 
if (($? != 0)); then
echo "server not running; starting server"
goneovim $1
fi
else 
echo "wrong file name"
fi

