#!/bin/sh
if [ -f $1 ]; then
nvr --nostart --servername  $(<~/servername.txt) --remote $1 
echo "trying to attaching to server"
(($? != 0)) && {echo "server not running; starting server"; goneovim $1 }
else 
echo "wrong file name"
fi

