lastupdatecheck: 0
recentrepos:
- /home/yasha/workspacemodules/thematrix
- /home/yasha/workspace
- /home/yashasavelyev/workspacemodules/novikov
startuppopupversion: 5
customcommandshistory: []
hidecommandlog: false
