// Generated by CoffeeScript 1.9.3
(function() {
  var documentReady;

  documentReady = function(func) {
    if (document.readyState === "loading") {
      return window.addEventListener("DOMContentLoaded", func);
    } else {
      return func();
    }
  };

  chrome.storage.sync.get("url", function(items) {
    return documentReady(function() {
      var ref;
      return document.location.href = (ref = items.url) != null ? ref : defaultURL;
    });
  });

}).call(this);
