"use strict";this.default_host=this.default_host||{};(function(_){var window=this;
try{
/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var aa,ba,ca,da,ea,fa,ia;aa=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};ba="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
ca=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("a");};da=ca(this);ea=function(a,b){if(b)a:{var c=da;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&ba(c,a,{configurable:!0,writable:!0,value:b})}};
ea("Symbol",function(a){if(a)return a;var b=function(g,h){this.g=g;ba(this,"description",{configurable:!0,writable:!0,value:h})};b.prototype.toString=function(){return this.g};var c="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",d=0,e=function(g){if(this instanceof e)throw new TypeError("b");return new b(c+(g||"")+"_"+d++,g)};return e});
ea("Symbol.iterator",function(a){if(a)return a;a=Symbol("c");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=da[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&ba(d.prototype,a,{configurable:!0,writable:!0,value:function(){return fa(aa(this))}})}return a});fa=function(a){a={next:a};a[Symbol.iterator]=function(){return this};return a};
_.n=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:aa(a)}};_.ha="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b};if("function"==typeof Object.setPrototypeOf)ia=Object.setPrototypeOf;else{var ja;a:{var ka={a:!0},la={};try{la.__proto__=ka;ja=la.a;break a}catch(a){}ja=!1}ia=ja?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError("d`"+a);return a}:null}_.ma=ia;
ea("Promise",function(a){function b(){this.g=null}function c(h){return h instanceof e?h:new e(function(k){k(h)})}if(a)return a;b.prototype.h=function(h){if(null==this.g){this.g=[];var k=this;this.j(function(){k.m()})}this.g.push(h)};var d=da.setTimeout;b.prototype.j=function(h){d(h,0)};b.prototype.m=function(){for(;this.g&&this.g.length;){var h=this.g;this.g=[];for(var k=0;k<h.length;++k){var l=h[k];h[k]=null;try{l()}catch(m){this.l(m)}}}this.g=null};b.prototype.l=function(h){this.j(function(){throw h;
})};var e=function(h){this.g=0;this.j=void 0;this.h=[];this.o=!1;var k=this.l();try{h(k.resolve,k.reject)}catch(l){k.reject(l)}};e.prototype.l=function(){function h(m){return function(u){l||(l=!0,m.call(k,u))}}var k=this,l=!1;return{resolve:h(this.D),reject:h(this.m)}};e.prototype.D=function(h){if(h===this)this.m(new TypeError("g"));else if(h instanceof e)this.H(h);else{a:switch(typeof h){case "object":var k=null!=h;break a;case "function":k=!0;break a;default:k=!1}k?this.K(h):this.G(h)}};e.prototype.K=
function(h){var k=void 0;try{k=h.then}catch(l){this.m(l);return}"function"==typeof k?this.M(k,h):this.G(h)};e.prototype.m=function(h){this.v(2,h)};e.prototype.G=function(h){this.v(1,h)};e.prototype.v=function(h,k){if(0!=this.g)throw Error("h`"+h+"`"+k+"`"+this.g);this.g=h;this.j=k;2===this.g&&this.U();this.A()};e.prototype.U=function(){var h=this;d(function(){if(h.ha()){var k=da.console;"undefined"!==typeof k&&k.error(h.j)}},1)};e.prototype.ha=function(){if(this.o)return!1;var h=da.CustomEvent,k=
da.Event,l=da.dispatchEvent;if("undefined"===typeof l)return!0;"function"===typeof h?h=new h("unhandledrejection",{cancelable:!0}):"function"===typeof k?h=new k("unhandledrejection",{cancelable:!0}):(h=da.document.createEvent("CustomEvent"),h.initCustomEvent("unhandledrejection",!1,!0,h));h.promise=this;h.reason=this.j;return l(h)};e.prototype.A=function(){if(null!=this.h){for(var h=0;h<this.h.length;++h)g.h(this.h[h]);this.h=null}};var g=new b;e.prototype.H=function(h){var k=this.l();h.Zb(k.resolve,
k.reject)};e.prototype.M=function(h,k){var l=this.l();try{h.call(k,l.resolve,l.reject)}catch(m){l.reject(m)}};e.prototype.then=function(h,k){function l(C,w){return"function"==typeof C?function(G){try{m(C(G))}catch(T){u(T)}}:w}var m,u,y=new e(function(C,w){m=C;u=w});this.Zb(l(h,m),l(k,u));return y};e.prototype.catch=function(h){return this.then(void 0,h)};e.prototype.Zb=function(h,k){function l(){switch(m.g){case 1:h(m.j);break;case 2:k(m.j);break;default:throw Error("i`"+m.g);}}var m=this;null==this.h?
g.h(l):this.h.push(l);this.o=!0};e.resolve=c;e.reject=function(h){return new e(function(k,l){l(h)})};e.race=function(h){return new e(function(k,l){for(var m=_.n(h),u=m.next();!u.done;u=m.next())c(u.value).Zb(k,l)})};e.all=function(h){var k=_.n(h),l=k.next();return l.done?c([]):new e(function(m,u){function y(G){return function(T){C[G]=T;w--;0==w&&m(C)}}var C=[],w=0;do C.push(void 0),w++,c(l.value).Zb(y(C.length-1),u),l=k.next();while(!l.done)})};return e});
var na=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
ea("WeakMap",function(a){function b(){}function c(l){var m=typeof l;return"object"===m&&null!==l||"function"===m}function d(l){if(!na(l,g)){var m=new b;ba(l,g,{value:m})}}function e(l){var m=Object[l];m&&(Object[l]=function(u){if(u instanceof b)return u;Object.isExtensible(u)&&d(u);return m(u)})}if(function(){if(!a||!Object.seal)return!1;try{var l=Object.seal({}),m=Object.seal({}),u=new a([[l,2],[m,3]]);if(2!=u.get(l)||3!=u.get(m))return!1;u.delete(l);u.set(m,4);return!u.has(l)&&4==u.get(m)}catch(y){return!1}}())return a;
var g="$jscomp_hidden_"+Math.random();e("freeze");e("preventExtensions");e("seal");var h=0,k=function(l){this.g=(h+=Math.random()+1).toString();if(l){l=_.n(l);for(var m;!(m=l.next()).done;)m=m.value,this.set(m[0],m[1])}};k.prototype.set=function(l,m){if(!c(l))throw Error("j");d(l);if(!na(l,g))throw Error("k`"+l);l[g][this.g]=m;return this};k.prototype.get=function(l){return c(l)&&na(l,g)?l[g][this.g]:void 0};k.prototype.has=function(l){return c(l)&&na(l,g)&&na(l[g],this.g)};k.prototype.delete=function(l){return c(l)&&
na(l,g)&&na(l[g],this.g)?delete l[g][this.g]:!1};return k});
ea("Map",function(a){if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var k=Object.seal({x:4}),l=new a(_.n([[k,"s"]]));if("s"!=l.get(k)||1!=l.size||l.get({x:4})||l.set({x:4},"t")!=l||2!=l.size)return!1;var m=l.entries(),u=m.next();if(u.done||u.value[0]!=k||"s"!=u.value[1])return!1;u=m.next();return u.done||4!=u.value[0].x||"t"!=u.value[1]||!m.next().done?!1:!0}catch(y){return!1}}())return a;var b=new WeakMap,c=function(k){this.h={};this.g=
g();this.size=0;if(k){k=_.n(k);for(var l;!(l=k.next()).done;)l=l.value,this.set(l[0],l[1])}};c.prototype.set=function(k,l){k=0===k?0:k;var m=d(this,k);m.list||(m.list=this.h[m.id]=[]);m.entry?m.entry.value=l:(m.entry={next:this.g,previous:this.g.previous,head:this.g,key:k,value:l},m.list.push(m.entry),this.g.previous.next=m.entry,this.g.previous=m.entry,this.size++);return this};c.prototype.delete=function(k){k=d(this,k);return k.entry&&k.list?(k.list.splice(k.index,1),k.list.length||delete this.h[k.id],
k.entry.previous.next=k.entry.next,k.entry.next.previous=k.entry.previous,k.entry.head=null,this.size--,!0):!1};c.prototype.clear=function(){this.h={};this.g=this.g.previous=g();this.size=0};c.prototype.has=function(k){return!!d(this,k).entry};c.prototype.get=function(k){return(k=d(this,k).entry)&&k.value};c.prototype.entries=function(){return e(this,function(k){return[k.key,k.value]})};c.prototype.keys=function(){return e(this,function(k){return k.key})};c.prototype.values=function(){return e(this,
function(k){return k.value})};c.prototype.forEach=function(k,l){for(var m=this.entries(),u;!(u=m.next()).done;)u=u.value,k.call(l,u[1],u[0],this)};c.prototype[Symbol.iterator]=c.prototype.entries;var d=function(k,l){var m=l&&typeof l;"object"==m||"function"==m?b.has(l)?m=b.get(l):(m=""+ ++h,b.set(l,m)):m="p_"+l;var u=k.h[m];if(u&&na(k.h,m))for(k=0;k<u.length;k++){var y=u[k];if(l!==l&&y.key!==y.key||l===y.key)return{id:m,list:u,index:k,entry:y}}return{id:m,list:u,index:-1,entry:void 0}},e=function(k,
l){var m=k.g;return fa(function(){if(m){for(;m.head!=k.g;)m=m.previous;for(;m.next!=m.head;)return m=m.next,{done:!1,value:l(m)};m=null}return{done:!0,value:void 0}})},g=function(){var k={};return k.previous=k.next=k.head=k},h=0;return c});ea("Array.prototype.find",function(a){return a?a:function(b,c){a:{var d=this;d instanceof String&&(d=String(d));for(var e=d.length,g=0;g<e;g++){var h=d[g];if(b.call(c,h,g,d)){b=h;break a}}b=void 0}return b}});
var oa=function(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var g=c++;return{value:b(g,a[g]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e};ea("Array.prototype.entries",function(a){return a?a:function(){return oa(this,function(b,c){return[b,c]})}});ea("Array.prototype.keys",function(a){return a?a:function(){return oa(this,function(b){return b})}});
ea("Array.from",function(a){return a?a:function(b,c,d){c=null!=c?c:function(k){return k};var e=[],g="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];if("function"==typeof g){b=g.call(b);for(var h=0;!(g=b.next()).done;)e.push(c.call(d,g.value,h++))}else for(g=b.length,h=0;h<g;h++)e.push(c.call(d,b[h],h));return e}});ea("Array.prototype.values",function(a){return a?a:function(){return oa(this,function(b,c){return c})}});
var pa="function"==typeof Object.assign?Object.assign:function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c];if(d)for(var e in d)na(d,e)&&(a[e]=d[e])}return a};ea("Object.assign",function(a){return a||pa});ea("Object.entries",function(a){return a?a:function(b){var c=[],d;for(d in b)na(b,d)&&c.push([d,b[d]]);return c}});ea("Object.is",function(a){return a?a:function(b,c){return b===c?0!==b||1/b===1/c:b!==b&&c!==c}});
ea("Array.prototype.includes",function(a){return a?a:function(b,c){var d=this;d instanceof String&&(d=String(d));var e=d.length;c=c||0;for(0>c&&(c=Math.max(c+e,0));c<e;c++){var g=d[c];if(g===b||Object.is(g,b))return!0}return!1}});ea("String.prototype.includes",function(a){return a?a:function(b,c){if(null==this)throw new TypeError("l`includes");if(b instanceof RegExp)throw new TypeError("m`includes");return-1!==this.indexOf(b,c||0)}});
ea("Set",function(a){if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var c=Object.seal({x:4}),d=new a(_.n([c]));if(!d.has(c)||1!=d.size||d.add(c)!=d||1!=d.size||d.add({x:4})!=d||2!=d.size)return!1;var e=d.entries(),g=e.next();if(g.done||g.value[0]!=c||g.value[1]!=c)return!1;g=e.next();return g.done||g.value[0]==c||4!=g.value[0].x||g.value[1]!=g.value[0]?!1:e.next().done}catch(h){return!1}}())return a;var b=function(c){this.g=new Map;if(c){c=
_.n(c);for(var d;!(d=c.next()).done;)this.add(d.value)}this.size=this.g.size};b.prototype.add=function(c){c=0===c?0:c;this.g.set(c,c);this.size=this.g.size;return this};b.prototype.delete=function(c){c=this.g.delete(c);this.size=this.g.size;return c};b.prototype.clear=function(){this.g.clear();this.size=0};b.prototype.has=function(c){return this.g.has(c)};b.prototype.entries=function(){return this.g.entries()};b.prototype.values=function(){return this.g.values()};b.prototype.keys=b.prototype.values;
b.prototype[Symbol.iterator]=b.prototype.values;b.prototype.forEach=function(c,d){var e=this;this.g.forEach(function(g){return c.call(d,g,g,e)})};return b});_.qa=_.qa||{};_.p=this||self;_.ra="closure_uid_"+(1E9*Math.random()>>>0);

}catch(e){_._DumpException(e)}
try{
/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var ua;_.sa=function(a){_.p.setTimeout(function(){throw a;},0)};_.ta=function(){};ua=function(a){return a};
_.va=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if("string"===typeof a)return"string"!==typeof b||1!=b.length?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};_.q=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e="string"===typeof a?a.split(""):a,g=0;g<d;g++)g in e&&b.call(c,e[g],g,a)};
_.wa=Array.prototype.map?function(a,b){return Array.prototype.map.call(a,b,void 0)}:function(a,b){for(var c=a.length,d=Array(c),e="string"===typeof a?a.split(""):a,g=0;g<c;g++)g in e&&(d[g]=b.call(void 0,e[g],g,a));return d};_.xa=Array.prototype.some?function(a,b,c){return Array.prototype.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e="string"===typeof a?a.split(""):a,g=0;g<d;g++)if(g in e&&b.call(c,e[g],g,a))return!0;return!1};
var ya;
_.za=RegExp("^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Adlm|Arab|Hebr|Nkoo|Rohg|Thaa))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)","i");
_.Aa=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]};
_.Ca=function(a,b){this.g=b===_.Ba?a:""};_.f=_.Ca.prototype;_.f.Ab=!0;_.f.yb=function(){return this.g.toString()};_.f.Lc=!0;_.f.Kb=function(){return 1};_.f.toString=function(){return this.g.toString()};_.Da=RegExp('^(?:audio/(?:3gpp2|3gpp|aac|L16|midi|mp3|mp4|mpeg|oga|ogg|opus|x-m4a|x-matroska|x-wav|wav|webm)|font/\\w+|image/(?:bmp|gif|jpeg|jpg|png|tiff|webp|x-icon)|video/(?:mpeg|mp4|ogg|webm|quicktime|x-matroska))(?:;\\w+=(?:\\w+|"[\\w;,= ]+"))*$',"i");_.Ba={};
_.Ea=new _.Ca("about:invalid#zClosurez",_.Ba);
a:{var Ga=_.p.navigator;if(Ga){var Ha=Ga.userAgent;if(Ha){_.Fa=Ha;break a}}_.Fa=""}_.r=function(a){return-1!=_.Fa.indexOf(a)};
_.Ia=function(){return _.r("Trident")||_.r("MSIE")};_.Ja=function(){return _.r("Firefox")||_.r("FxiOS")};_.La=function(){return _.r("Safari")&&!(_.Ka()||_.r("Coast")||_.r("Opera")||_.r("Edge")||_.r("Edg/")||_.r("OPR")||_.Ja()||_.r("Silk")||_.r("Android"))};_.Ka=function(){return(_.r("Chrome")||_.r("CriOS"))&&!_.r("Edge")};
var Ma;Ma={};_.Na=function(a,b,c){this.g=c===Ma?a:"";this.h=b;this.Ab=this.Lc=!0};_.Na.prototype.Kb=function(){return this.h};_.Na.prototype.yb=function(){return this.g.toString()};_.Na.prototype.toString=function(){return this.g.toString()};_.Oa=function(a){return a instanceof _.Na&&a.constructor===_.Na?a.g:"type_error:SafeHtml"};
_.Pa=function(a,b){if(void 0===ya){var c=null;var d=_.p.trustedTypes;if(d&&d.createPolicy){try{c=d.createPolicy("goog#html",{createHTML:ua,createScript:ua,createScriptURL:ua})}catch(e){_.p.console&&_.p.console.error(e.message)}ya=c}else ya=c}a=(c=ya)?c.createHTML(a):a;return new _.Na(a,b,Ma)};_.Qa=new _.Na(_.p.trustedTypes&&_.p.trustedTypes.emptyHTML||"",0,Ma);_.Ra=_.Pa("<br>",0);
_.Sa=function(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}}(function(){var a=document.createElement("div"),b=document.createElement("div");b.appendChild(document.createElement("div"));a.appendChild(b);b=a.firstChild.firstChild;a.innerHTML=_.Oa(_.Qa);return!b.parentElement});
_.Ta=String.prototype.repeat?function(a,b){return a.repeat(b)}:function(a,b){return Array(b+1).join(a)};
_.Ua=function(){return _.r("iPhone")&&!_.r("iPod")&&!_.r("iPad")};_.Va=function(){return _.Ua()||_.r("iPad")||_.r("iPod")};_.Wa=function(){return _.r("Macintosh")};_.Xa=function(){return _.r("Windows")};
_.Ya=function(a){_.Ya[" "](a);return a};_.Ya[" "]=_.ta;
var fb,lb;_.Za=_.r("Opera");_.$a=_.Ia();_.ab=_.r("Edge");_.bb=_.r("Gecko")&&!(-1!=_.Fa.toLowerCase().indexOf("webkit")&&!_.r("Edge"))&&!(_.r("Trident")||_.r("MSIE"))&&!_.r("Edge");_.cb=-1!=_.Fa.toLowerCase().indexOf("webkit")&&!_.r("Edge");_.db=_.cb&&_.r("Mobile");fb=_.p.navigator||null;_.eb=fb&&fb.platform||"";_.gb=_.Wa();_.hb=_.Xa();_.ib=_.r("Android");_.jb=_.Ua();_.kb=_.r("iPad");
a:{var mb="",nb=function(){var a=_.Fa;if(_.bb)return/rv:([^\);]+)(\)|;)/.exec(a);if(_.ab)return/Edge\/([\d\.]+)/.exec(a);if(_.$a)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(_.cb)return/WebKit\/(\S+)/.exec(a);if(_.Za)return/(?:Version)[ \/]?(\S+)/.exec(a)}();nb&&(mb=nb?nb[1]:"");if(_.$a){var ob,pb=_.p.document;ob=pb?pb.documentMode:void 0;if(null!=ob&&ob>parseFloat(mb)){lb=String(ob);break a}}lb=mb}_.rb=lb;
_.sb=_.Ja();_.tb=_.Ua()||_.r("iPod");_.ub=_.r("iPad");_.vb=_.r("Android")&&!(_.Ka()||_.Ja()||_.r("Opera")||_.r("Silk"));_.wb=_.Ka();_.xb=_.La()&&!_.Va();
var zb;_.yb="function"===typeof Uint8Array;zb={Mc:{value:!0,configurable:!0}};_.Ab=function(a){Array.isArray(a)&&!Object.isFrozen(a)&&Object.defineProperties(a,zb);return a};
_.Bb=Object.freeze(_.Ab([]));

}catch(e){_._DumpException(e)}
try{
var Ib,Lb,Nb,Sb,Tb,Vb,Zb,ac,bc,dc,hc,Hb,jc,kc,lc,Pb,rc,xc,zc,Cc,Fc;_.Cb=function(a,b){if(Error.captureStackTrace)Error.captureStackTrace(this,_.Cb);else{var c=Error().stack;c&&(this.stack=c)}a&&(this.message=String(a));void 0!==b&&(this.cause=b);this.g=!0};_.Db=function(a,b){return 0<=(0,_.va)(a,b)};_.Eb=function(a,b){return 1==Array.prototype.splice.call(a,b,1).length};_.Fb=function(a,b){b=(0,_.va)(a,b);var c;(c=0<=b)&&_.Eb(a,b);return c};
_.Gb=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};Ib=function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c];if(Hb(d)){var e=a.length||0,g=d.length||0;a.length=e+g;for(var h=0;h<g;h++)a[e+h]=d[h]}else a.push(d)}};Lb=function(a){for(var b=0,c=0,d={};c<a.length;){var e=a[c++],g=_.Jb(e)?"o"+_.Kb(e):(typeof e).charAt(0)+e;Object.prototype.hasOwnProperty.call(d,g)||(d[g]=!0,a[b++]=e)}a.length=b};
_.Mb=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)};Nb=function(a,b){for(var c in a)if(b.call(void 0,a[c],c,a))return!0;return!1};_.Ob=function(a){var b={},c;for(c in a)b[c]=a[c];return b};_.Qb=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var g=0;g<Pb.length;g++)c=Pb[g],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};Sb=function(a,b,c){return"object"===typeof a?_.yb&&!Array.isArray(a)&&a instanceof Uint8Array?c(a):_.Rb(a,b,c):b(a)};
_.Rb=function(a,b,c){if(Array.isArray(a)){for(var d=Array(a.length),e=0;e<a.length;e++){var g=a[e];null!=g&&(d[e]=Sb(g,b,c))}Array.isArray(a)&&a.Mc&&_.Ab(d);return d}d={};for(e in a)g=a[e],null!=g&&(d[e]=Sb(g,b,c));return d};Tb=function(a){return _.Rb(a,function(b){return b},function(b){return new Uint8Array(b)})};Vb=function(a){return _.Rb(a,function(b){return"number"===typeof b?isFinite(b)?b:String(b):b},function(b){return _.Ub(b)})};_.t=function(a){a&&"function"==typeof a.dispose&&a.dispose()};
_.v=function(a,b){for(var c=[],d=0;d<arguments.length;d++)if(arguments[d]instanceof Error)c.push(arguments[d].stack);else if("object"==typeof arguments[d])try{c.push(JSON.stringify(arguments[d]))}catch(e){c.push("_error_("+e+")")}else c.push(arguments[d]);window.console&&(d=new Date,d=Wb("%02d-%02d ",d.getMonth()+1,d.getDate())+d.toLocaleTimeString(void 0,{hour12:!1})+Wb(".%03d",d.getMilliseconds()),window.console.log(d+" info: "+Wb.apply({},c)))};
_.Yb=function(a,b){_.x.call(this);this.o=b||Xb();this.l=this.g="";this.h=this.j=null;this.v=a;this.m=new _.z(this);_.A(this,this.m);this.m.listen(window,"message",this.A)};Zb=function(a,b,c){_.x.call(this);this.h=a;a=_.B(b,3);b=_.B(b,1);this.g=new _.Yb((0,_.D)(this.j,this),b);this.g.g=a;c&&this.g.Sa(c.origin,c.source);_.A(this,this.g)};ac=function(a,b,c){var d=!1;void 0!==_.B(b,2)?4==_.B(b,2)&&(d=!0):d=_.wb;return d?new $b(a,b,c):new Zb(a,b,c)};bc=function(a){_.x.call(this);this.g=a;this.m=!1};
dc=function(a){bc.call(this,a);this.ma=null;this.h=0;null===cc&&(cc=null)};_.fc=function(){var a=new ec("Google_Hangouts_Chrome");a.Gb(chrome.runtime.id);a.Qa(chrome.runtime.getManifest().version);null==a.g[1]&&(a.g[1]=new dc(a.config));a.g[1].enable();a.ac().Bd(!1).zd(100).ad("Script error.",0).enable();a.Ya=a};_.ic=function(a){if(!a.vb){var b;for(b=a.constructor;b&&!b.lb;)b=b.X&&b.X.constructor;b.lb.hd||(b.lb.hd=gc(b));b=new b.lb.hd(a);a.vb=b;a.Fc||(a.Fc=hc)}};hc=function(a){return this.vb.Fc(a)};
_.E=function(a,b){a.prototype=(0,_.ha)(b.prototype);a.prototype.constructor=a;if(_.ma)(0,_.ma)(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.X=b.prototype};_.Jb=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b};Hb=function(a){var b=typeof a;b="object"!=b?b:a?Array.isArray(a)?"array":b:"null";return"array"==b||"object"==b&&"number"==typeof a.length};jc=0;
_.Kb=function(a){return Object.prototype.hasOwnProperty.call(a,_.ra)&&a[_.ra]||(a[_.ra]=++jc)};kc=function(a,b,c){return a.call.apply(a.bind,arguments)};lc=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,d);return a.apply(b,e)}}return function(){return a.apply(b,arguments)}};
_.D=function(a,b,c){Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?_.D=kc:_.D=lc;return _.D.apply(null,arguments)};_.mc=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var d=c.slice();d.push.apply(d,arguments);return a.apply(this,d)}};
_.nc=function(a,b){a=a.split(".");var c=_.p;a[0]in c||"undefined"==typeof c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)a.length||void 0===b?c[d]&&c[d]!==Object.prototype[d]?c=c[d]:c=c[d]={}:c[d]=b};_.F=function(a,b){function c(){}c.prototype=b.prototype;a.X=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Gf=function(d,e,g){for(var h=Array(arguments.length-2),k=2;k<arguments.length;k++)h[k-2]=arguments[k];return b.prototype[e].apply(d,h)}};_.F(_.Cb,Error);
_.Cb.prototype.name="CustomError";Pb="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");_.oc=function(a,b){return 0==a.lastIndexOf(b,0)};_.pc=function(a,b){var c=a.length-b.length;return 0<=c&&a.indexOf(b,c)==c};_.qc=function(a){return/^[\s\xa0]*$/.test(a)};rc=function(a,b){return a<b?-1:a>b?1:0};
_.sc=function(a,b){var c=0;a=(0,_.Aa)(String(a)).split(".");b=(0,_.Aa)(String(b)).split(".");for(var d=Math.max(a.length,b.length),e=0;0==c&&e<d;e++){var g=a[e]||"",h=b[e]||"";do{g=/(\d*)(\D*)(.*)/.exec(g)||["","","",""];h=/(\d*)(\D*)(.*)/.exec(h)||["","","",""];if(0==g[0].length&&0==h[0].length)break;c=rc(0==g[1].length?0:parseInt(g[1],10),0==h[1].length?0:parseInt(h[1],10))||rc(0==g[2].length,0==h[2].length)||rc(g[2],h[2]);g=g[3];h=h[3]}while(0==c)}return c};_.tc=function(a){return null==a?"":String(a)};
_.uc=function(){return _.r("CrOS")};
_.vc=function(){var a=_.Fa,b="";_.Xa()?(b=/Windows (?:NT|Phone) ([0-9.]+)/,b=(a=b.exec(a))?a[1]:"0.0"):_.Va()?(b=/(?:iPhone|iPod|iPad|CPU)\s+OS\s+(\S+)/,b=(a=b.exec(a))&&a[1].replace(/_/g,".")):_.Wa()?(b=/Mac OS X ([0-9_.]+)/,b=(a=b.exec(a))?a[1].replace(/_/g,"."):"10"):-1!=_.Fa.toLowerCase().indexOf("kaios")?(b=/(?:KaiOS)\/(\S+)/i,b=(a=b.exec(a))&&a[1]):_.r("Android")?(b=/Android\s+([^\);]+)(\)|;)/,b=(a=b.exec(a))&&a[1]):_.uc()&&(b=/(?:CrOS\s+(?:i686|x86_64)\s+([0-9.]+))/,b=(a=b.exec(a))&&a[1]);
return b||""};_.wc=function(a,b,c){return Object.prototype.hasOwnProperty.call(a,b)?a[b]:a[b]=c(b)};xc={};_.yc=function(a){return _.wc(xc,a,function(){return 0<=_.sc(_.rb,a)})};zc={};_.Ac=null;_.Bc=function(){if(!_.Ac){_.Ac={};for(var a="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split(""),b=["+/=","+/","-_=","-_.","-_"],c=0;5>c;c++){var d=a.concat(b[c].split(""));zc[c]=d;for(var e=0;e<d.length;e++){var g=d[e];void 0===_.Ac[g]&&(_.Ac[g]=e)}}}};
_.Ub=function(a){var b;void 0===b&&(b=0);_.Bc();b=zc[b];for(var c=Array(Math.floor(a.length/3)),d=b[64]||"",e=0,g=0;e<a.length-2;e+=3){var h=a[e],k=a[e+1],l=a[e+2],m=b[h>>2];h=b[(h&3)<<4|k>>4];k=b[(k&15)<<2|l>>6];l=b[l&63];c[g++]=m+h+k+l}m=0;l=d;switch(a.length-e){case 2:m=a[e+1],l=b[(m&15)<<2]||d;case 1:a=a[e],c[g]=b[a>>2]+b[(a&3)<<4|m>>4]+l+d}return c.join("")};_.Ec=function(a){var b=a.m+a.l;a.j[b]||(a.h=a.j[b]={})};
Fc=function(a,b){switch(typeof b){case "number":return isFinite(b)?b:String(b);case "object":if(_.yb&&null!=b&&b instanceof Uint8Array)return _.Ub(b)}return b};
_.I=function(a,b,c,d){var e=_.Dc;_.Dc=null;a||(a=e);e=this.constructor.messageId;a||(a=e?[e]:[]);this.l=e?0:-1;this.g=null;this.j=a;a:{e=this.j.length;a=e-1;if(e&&(e=this.j[a],!(null===e||"object"!=typeof e||Array.isArray(e)||_.yb&&e instanceof Uint8Array))){this.m=a-this.l;this.h=e;break a}void 0!==b&&-1<b?(this.m=Math.max(b,a+1-this.l),this.h=null):this.m=Number.MAX_VALUE}if(c)for(b=0;b<c.length;b++)a=c[b],a<this.m?(a+=this.l,(e=this.j[a])?_.Ab(e):this.j[a]=_.Bb):(_.Ec(this),(e=this.h[a])?_.Ab(e):
this.h[a]=_.Bb);if(d&&d.length)for(c=0;c<d.length;c++){a=b=void 0;e=d[c];for(var g=0;g<e.length;g++){var h=e[g],k=_.B(this,h);null!=k&&(a=h,b=k,_.H(this,h,void 0))}a&&_.H(this,a,b)}};_.B=function(a,b){if(b<a.m){b+=a.l;var c=a.j[b];return c!==_.Bb?c:a.j[b]=_.Ab([])}if(a.h)return c=a.h[b],c!==_.Bb?c:a.h[b]=_.Ab([])};_.J=function(a,b){a=_.B(a,b);return null==a?a:!!a};_.Gc=function(a,b,c){a=_.B(a,b);return null==a?c:a};_.H=function(a,b,c){b<a.m?a.j[b+a.l]=c:(_.Ec(a),a.h[b]=c);return a};
_.K=function(a,b,c){a.g||(a.g={});if(!a.g[c]){var d=_.B(a,c);d&&(a.g[c]=new b(d))}return a.g[c]};_.L=function(a,b,c){a.g||(a.g={});var d=c?_.Hc(c,!1):c;a.g[b]=c;return _.H(a,b,d)};_.I.prototype.toJSON=function(){var a=_.Hc(this,!1);return Cc?a:Vb(a)};_.Hc=function(a,b){if(a.g)for(var c in a.g){var d=a.g[c];if(Array.isArray(d))for(var e=0;e<d.length;e++)d[e]&&_.Hc(d[e],b);else d&&_.Hc(d,b)}return a.j};_.Ic=function(a){Cc=!0;try{return JSON.stringify(a.toJSON(),Fc)}finally{Cc=!1}};
_.I.prototype.toString=function(){return _.Hc(this,!1).toString()};_.Jc=function(a,b,c){return _.Gc(a,b,void 0===c?"":c)};
_.Kc="function"===typeof Uint8Array.prototype.slice;
/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
_.x=function(){this.ha=this.ha;this.G=this.G};_.x.prototype.ha=!1;_.x.prototype.isDisposed=function(){return this.ha};_.x.prototype.dispose=function(){this.ha||(this.ha=!0,this.F())};_.A=function(a,b){_.M(a,_.mc(_.t,b))};_.M=function(a,b,c){a.ha?void 0!==c?b.call(c):b():(a.G||(a.G=[]),a.G.push(void 0!==c?(0,_.D)(b,c):b))};_.x.prototype.F=function(){if(this.G)for(;this.G.length;)this.G.shift()()};
var Lc=function(a,b){this.j=a;this.l=b;this.h=0;this.g=null};Lc.prototype.get=function(){if(0<this.h){this.h--;var a=this.g;this.g=a.next;a.next=null}else a=this.j();return a};var Mc=function(a,b){a.l(b);100>a.h&&(a.h++,b.next=a.g,a.g=b)};
var Qc;_.Nc=[];_.Oc=[];_.Pc=!1;Qc=function(a){_.Nc[_.Nc.length]=a;if(_.Pc)for(var b=0;b<_.Oc.length;b++)a((0,_.D)(_.Oc[b].ea,_.Oc[b]))};
try{(new self.OffscreenCanvas(0,0)).getContext("2d")}catch(a){}
;var Tc;_.Sc=function(a,b){var c=b||document;if(c.getElementsByClassName)a=c.getElementsByClassName(a)[0];else{c=document;var d=b||c;a=d.querySelectorAll&&d.querySelector&&a?d.querySelector(a?"."+a:""):_.Rc(c,"*",a,b)[0]||null}return a||null};
_.Rc=function(a,b,c,d){a=d||a;b=b&&"*"!=b?String(b).toUpperCase():"";if(a.querySelectorAll&&a.querySelector&&(b||c))return a.querySelectorAll(b+(c?"."+c:""));if(c&&a.getElementsByClassName){a=a.getElementsByClassName(c);if(b){d={};for(var e=0,g=0,h;h=a[g];g++)b==h.nodeName&&(d[e++]=h);d.length=e;return d}return a}a=a.getElementsByTagName(b||"*");if(c){d={};for(g=e=0;h=a[g];g++)b=h.className,"function"==typeof b.split&&_.Db(b.split(/\s+/),c)&&(d[e++]=h);d.length=e;return d}return a};
_.Uc=function(a,b){_.Mb(b,function(c,d){c&&"object"==typeof c&&c.Ab&&(c=c.yb());"style"==d?a.style.cssText=c:"class"==d?a.className=c:"for"==d?a.htmlFor=c:Tc.hasOwnProperty(d)?a.setAttribute(Tc[d],c):_.oc(d,"aria-")||_.oc(d,"data-")?a.setAttribute(d,c):a[d]=c})};Tc={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};
_.Vc=function(a,b){b=String(b);"application/xhtml+xml"===a.contentType&&(b=b.toLowerCase());return a.createElement(b)};_.Xc=function(a){for(var b;b=a.firstChild;)a.removeChild(b)};_.Yc=function(a){this.g=a||_.p.document||document};_.Yc.prototype.I=function(a){return"string"===typeof a?this.g.getElementById(a):a};_.Yc.prototype.setProperties=_.Uc;_.Zc=function(a,b){return _.Vc(a.g,b)};
_.Yc.prototype.getChildren=function(a){return void 0!=a.children?a.children:Array.prototype.filter.call(a.childNodes,function(b){return 1==b.nodeType})};_.Yc.prototype.contains=function(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a};
var ad,bd,$c;_.cd=function(a,b){var c=a;b&&(c=(0,_.D)(a,b));c=$c(c);"function"!==typeof _.p.setImmediate||_.p.Window&&_.p.Window.prototype&&!_.r("Edge")&&_.p.Window.prototype.setImmediate==_.p.setImmediate?(ad||(ad=bd()),ad(c)):_.p.setImmediate(c)};
bd=function(){var a=_.p.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&!_.r("Presto")&&(a=function(){var e=_.Vc(document,"IFRAME");e.style.display="none";document.documentElement.appendChild(e);var g=e.contentWindow;e=g.document;e.open();e.close();var h="callImmediate"+Math.random(),k="file:"==g.location.protocol?"*":g.location.protocol+"//"+g.location.host;e=(0,_.D)(function(l){if(("*"==k||l.origin==k)&&l.data==h)this.port1.onmessage()},
this);g.addEventListener("message",e,!1);this.port1={};this.port2={postMessage:function(){g.postMessage(h,k)}}});if("undefined"!==typeof a&&!_.Ia()){var b=new a,c={},d=c;b.port1.onmessage=function(){if(void 0!==c.next){c=c.next;var e=c.ed;c.ed=null;e()}};return function(e){d.next={ed:e};d=d.next;b.port2.postMessage(0)}}return function(e){_.p.setTimeout(e,0)}};$c=function(a){return a};Qc(function(a){$c=a});
var dd=function(){this.h=this.g=null};dd.prototype.add=function(a,b){var c=ed.get();c.set(a,b);this.h?this.h.next=c:this.g=c;this.h=c};dd.prototype.remove=function(){var a=null;this.g&&(a=this.g,this.g=this.g.next,this.g||(this.h=null),a.next=null);return a};var ed=new Lc(function(){return new fd},function(a){return a.reset()}),fd=function(){this.next=this.scope=this.g=null};fd.prototype.set=function(a,b){this.g=a;this.scope=b;this.next=null};
fd.prototype.reset=function(){this.next=this.scope=this.g=null};
var kd=function(a,b){gd||hd();id||(gd(),id=!0);jd.add(a,b)},gd,hd=function(){if(_.p.Promise&&_.p.Promise.resolve){var a=_.p.Promise.resolve(void 0);gd=function(){a.then(ld)}}else gd=function(){_.cd(ld)}},id=!1,jd=new dd,ld=function(){for(var a;a=jd.remove();){try{a.g.call(a.scope)}catch(b){_.sa(b)}Mc(ed,a)}id=!1};
var md=function(a){if(!a)return!1;try{return!!a.$goog_Thenable}catch(b){return!1}};
var pd,qd,rd,yd,vd,Cd,Bd,zd,Ad,Ed,Dd,Fd;_.od=function(a){this.g=0;this.o=void 0;this.l=this.h=this.j=null;this.m=this.G=!1;if(a!=_.ta)try{var b=this;a.call(void 0,function(c){_.nd(b,2,c)},function(c){_.nd(b,3,c)})}catch(c){_.nd(this,3,c)}};pd=function(){this.next=this.j=this.h=this.m=this.g=null;this.l=!1};pd.prototype.reset=function(){this.j=this.h=this.m=this.g=null;this.l=!1};qd=new Lc(function(){return new pd},function(a){a.reset()});rd=function(a,b,c){var d=qd.get();d.m=a;d.h=b;d.j=c;return d};
_.td=function(){var a,b,c=new _.od(function(d,e){a=d;b=e});return new sd(c,a,b)};_.od.prototype.then=function(a,b,c){return _.ud(this,"function"===typeof a?a:null,"function"===typeof b?b:null,c)};_.od.prototype.$goog_Thenable=!0;_.wd=function(a,b,c){b=rd(b,b,c);b.l=!0;vd(a,b)};_.od.prototype.cancel=function(a){if(0==this.g){var b=new _.xd(a);kd(function(){yd(this,b)},this)}};
yd=function(a,b){if(0==a.g)if(a.j){var c=a.j;if(c.h){for(var d=0,e=null,g=null,h=c.h;h&&(h.l||(d++,h.g==a&&(e=h),!(e&&1<d)));h=h.next)e||(g=h);e&&(0==c.g&&1==d?yd(c,b):(g?(d=g,d.next==c.l&&(c.l=d),d.next=d.next.next):zd(c),Ad(c,e,3,b)))}a.j=null}else _.nd(a,3,b)};vd=function(a,b){a.h||2!=a.g&&3!=a.g||Bd(a);a.l?a.l.next=b:a.h=b;a.l=b};
_.ud=function(a,b,c,d){var e=rd(null,null,null);e.g=new _.od(function(g,h){e.m=b?function(k){try{var l=b.call(d,k);g(l)}catch(m){h(m)}}:g;e.h=c?function(k){try{var l=c.call(d,k);void 0===l&&k instanceof _.xd?h(k):g(l)}catch(m){h(m)}}:h});e.g.j=a;vd(a,e);return e.g};_.od.prototype.A=function(a){this.g=0;_.nd(this,2,a)};_.od.prototype.ha=function(a){this.g=0;_.nd(this,3,a)};
_.nd=function(a,b,c){if(0==a.g){a===c&&(b=3,c=new TypeError("q"));a.g=1;a:{var d=c,e=a.A,g=a.ha;if(d instanceof _.od){vd(d,rd(e||_.ta,g||null,a));var h=!0}else if(md(d))d.then(e,g,a),h=!0;else{if(_.Jb(d))try{var k=d.then;if("function"===typeof k){Cd(d,k,e,g,a);h=!0;break a}}catch(l){g.call(a,l);h=!0;break a}h=!1}}h||(a.o=c,a.g=b,a.j=null,Bd(a),3!=b||c instanceof _.xd||Dd(a,c))}};
Cd=function(a,b,c,d,e){var g=!1,h=function(l){g||(g=!0,c.call(e,l))},k=function(l){g||(g=!0,d.call(e,l))};try{b.call(a,h,k)}catch(l){k(l)}};Bd=function(a){a.G||(a.G=!0,kd(a.v,a))};zd=function(a){var b=null;a.h&&(b=a.h,a.h=b.next,b.next=null);a.h||(a.l=null);return b};_.od.prototype.v=function(){for(var a;a=zd(this);)Ad(this,a,this.g,this.o);this.G=!1};
Ad=function(a,b,c,d){if(3==c&&b.h&&!b.l)for(;a&&a.m;a=a.j)a.m=!1;if(b.g)b.g.j=null,Ed(b,c,d);else try{b.l?b.m.call(b.j):Ed(b,c,d)}catch(e){Fd.call(null,e)}Mc(qd,b)};Ed=function(a,b,c){2==b?a.m.call(a.j,c):a.h&&a.h.call(a.j,c)};Dd=function(a,b){a.m=!0;kd(function(){a.m&&Fd.call(null,b)})};Fd=_.sa;_.xd=function(a){_.Cb.call(this,a);this.g=!1};_.F(_.xd,_.Cb);_.xd.prototype.name="cancel";var sd=function(a,b,c){this.promise=a;this.resolve=b;this.reject=c};
/*

 Copyright 2005, 2007 Bob Ippolito. All Rights Reserved.
 Copyright The Closure Library Authors.
 SPDX-License-Identifier: MIT
*/
_.Gd=function(a){this.G=[];this.U=a;this.l=this.D=!1;this.h=void 0;this.A=this.H=this.v=!1;this.o=0;this.g=null;this.m=0};_.Gd.prototype.cancel=function(a){if(this.Wa())this.h instanceof _.Gd&&this.h.cancel();else{if(this.g){var b=this.g;delete this.g;a?b.cancel(a):(b.m--,0>=b.m&&b.cancel())}this.U?this.U.call(null,this):this.A=!0;this.Wa()||this.K(new _.Hd(this))}};_.Gd.prototype.ha=function(a,b){this.v=!1;Id(this,a,b)};
var Id=function(a,b,c){a.D=!0;a.h=c;a.l=!b;Jd(a)},Ld=function(a){if(a.Wa()){if(!a.A)throw new Kd(a);a.A=!1}};_.Gd.prototype.callback=function(a){Ld(this);Id(this,!0,a)};_.Gd.prototype.K=function(a){Ld(this);Id(this,!1,a)};_.Nd=function(a,b,c){_.Md(a,b,null,c)};_.Md=function(a,b,c,d){a.G.push([b,c,d]);a.Wa()&&Jd(a)};_.Gd.prototype.then=function(a,b,c){var d,e,g=new _.od(function(h,k){e=h;d=k});_.Md(this,e,function(h){h instanceof _.Hd?g.cancel():d(h)});return g.then(a,b,c)};
_.Gd.prototype.$goog_Thenable=!0;_.Gd.prototype.j=function(a){var b=new _.Gd;_.Md(this,b.callback,b.K,b);a&&(b.g=this,this.m++);return b};_.Gd.prototype.Wa=function(){return this.D};_.Gd.prototype.isError=function(a){return a instanceof Error};
var Od=function(a){return _.xa(a.G,function(b){return"function"===typeof b[1]})},Jd=function(a){if(a.o&&a.Wa()&&Od(a)){var b=a.o,c=Pd[b];c&&(_.p.clearTimeout(c.g),delete Pd[b]);a.o=0}a.g&&(a.g.m--,delete a.g);b=a.h;for(var d=c=!1;a.G.length&&!a.v;){var e=a.G.shift(),g=e[0],h=e[1];e=e[2];if(g=a.l?h:g)try{var k=g.call(e||null,b);void 0!==k&&(a.l=a.l&&(k==b||a.isError(k)),a.h=b=k);if(md(b)||"function"===typeof _.p.Promise&&b instanceof _.p.Promise)d=!0,a.v=!0}catch(l){b=l,a.l=!0,Od(a)||(c=!0)}}a.h=b;
d&&(k=(0,_.D)(a.ha,a,!0),d=(0,_.D)(a.ha,a,!1),b instanceof _.Gd?(_.Md(b,k,d),b.H=!0):b.then(k,d));c&&(b=new Qd(b),Pd[b.g]=b,a.o=b.g)},Kd=function(){_.Cb.call(this)};_.F(Kd,_.Cb);Kd.prototype.message="Deferred has already fired";Kd.prototype.name="AlreadyCalledError";_.Hd=function(){_.Cb.call(this)};_.F(_.Hd,_.Cb);_.Hd.prototype.message="Deferred was canceled";_.Hd.prototype.name="CanceledError";var Qd=function(a){this.g=_.p.setTimeout((0,_.D)(this.j,this),0);this.h=a};
Qd.prototype.j=function(){delete Pd[this.g];throw this.h;};var Pd={};
var Sd,Rd,Vd,Wd,Ud;_.Td=function(a){var b=[];Rd(new Sd,a,b);return b.join("")};Sd=function(){};
Rd=function(a,b,c){if(null==b)c.push("null");else{if("object"==typeof b){if(Array.isArray(b)){var d=b;b=d.length;c.push("[");for(var e="",g=0;g<b;g++)c.push(e),Rd(a,d[g],c),e=",";c.push("]");return}if(b instanceof String||b instanceof Number||b instanceof Boolean)b=b.valueOf();else{c.push("{");e="";for(d in b)Object.prototype.hasOwnProperty.call(b,d)&&(g=b[d],"function"!=typeof g&&(c.push(e),Ud(d,c),c.push(":"),Rd(a,g,c),e=","));c.push("}");return}}switch(typeof b){case "string":Ud(b,c);break;case "number":c.push(isFinite(b)&&
!isNaN(b)?String(b):"null");break;case "boolean":c.push(String(b));break;case "function":c.push("null");break;default:throw Error("r`"+typeof b);}}};Vd={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"};Wd=/\uffff/.test("\uffff")?/[\\"\x00-\x1f\x7f-\uffff]/g:/[\\"\x00-\x1f\x7f-\xff]/g;Ud=function(a,b){b.push('"',a.replace(Wd,function(c){var d=Vd[c];d||(d="\\u"+(c.charCodeAt(0)|65536).toString(16).substr(1),Vd[c]=d);return d}),'"')};
_.Yd=function(a,b){this.type="undefined"!=typeof _.Xd&&a instanceof _.Xd?String(a):a;this.g=this.target=b;this.defaultPrevented=this.j=!1};_.Yd.prototype.l=function(){this.j=!0};_.Yd.prototype.h=function(){this.defaultPrevented=!0};
var Zd=function(){if(!_.p.addEventListener||!Object.defineProperty)return!1;var a=!1,b=Object.defineProperty({},"passive",{get:function(){a=!0}});try{_.p.addEventListener("test",_.ta,b),_.p.removeEventListener("test",_.ta,b)}catch(c){}return a}();
var $d=function(a,b){_.Yd.call(this,a?a.type:"");this.relatedTarget=this.g=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=0;this.key="";this.keyCode=0;this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.state=null;this.pointerId=0;this.pointerType="";this.xa=null;a&&this.init(a,b)};_.F($d,_.Yd);var ae={2:"touch",3:"pen",4:"mouse"};
$d.prototype.init=function(a,b){var c=this.type=a.type,d=a.changedTouches&&a.changedTouches.length?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.g=b;if(b=a.relatedTarget){if(_.bb){a:{try{_.Ya(b.nodeName);var e=!0;break a}catch(g){}e=!1}e||(b=null)}}else"mouseover"==c?b=a.fromElement:"mouseout"==c&&(b=a.toElement);this.relatedTarget=b;d?(this.clientX=void 0!==d.clientX?d.clientX:d.pageX,this.clientY=void 0!==d.clientY?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=d.screenY||
0):(this.clientX=void 0!==a.clientX?a.clientX:a.pageX,this.clientY=void 0!==a.clientY?a.clientY:a.pageY,this.screenX=a.screenX||0,this.screenY=a.screenY||0);this.button=a.button;this.keyCode=a.keyCode||0;this.key=a.key||"";this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.pointerId=a.pointerId||0;this.pointerType="string"===typeof a.pointerType?a.pointerType:ae[a.pointerType]||"";this.state=a.state;this.xa=a;a.defaultPrevented&&$d.X.h.call(this)};
$d.prototype.l=function(){$d.X.l.call(this);this.xa.stopPropagation?this.xa.stopPropagation():this.xa.cancelBubble=!0};$d.prototype.h=function(){$d.X.h.call(this);var a=this.xa;a.preventDefault?a.preventDefault():a.returnValue=!1};
var be;be="closure_listenable_"+(1E6*Math.random()|0);_.ce=function(a){return!(!a||!a[be])};
var de=0;
var ee=function(a,b,c,d,e){this.listener=a;this.proxy=null;this.src=b;this.type=c;this.capture=!!d;this.cc=e;this.key=++de;this.removed=this.Yb=!1},fe=function(a){a.removed=!0;a.listener=null;a.proxy=null;a.src=null;a.cc=null};
var ge=function(a){this.src=a;this.g={};this.h=0},ke,he;ge.prototype.add=function(a,b,c,d,e){var g=a.toString();a=this.g[g];a||(a=this.g[g]=[],this.h++);var h=he(a,b,d,e);-1<h?(b=a[h],c||(b.Yb=!1)):(b=new ee(b,this.src,g,!!d,e),b.Yb=c,a.push(b));return b};ge.prototype.remove=function(a,b,c,d){a=a.toString();if(!(a in this.g))return!1;var e=this.g[a];b=he(e,b,c,d);return-1<b?(fe(e[b]),_.Eb(e,b),0==e.length&&(delete this.g[a],this.h--),!0):!1};
var ie=function(a,b){var c=b.type;c in a.g&&_.Fb(a.g[c],b)&&(fe(b),0==a.g[c].length&&(delete a.g[c],a.h--))};ge.prototype.removeAll=function(a){a=a&&a.toString();var b=0,c;for(c in this.g)if(!a||c==a){for(var d=this.g[c],e=0;e<d.length;e++)++b,fe(d[e]);delete this.g[c];this.h--}return b};_.je=function(a,b,c,d,e){a=a.g[b.toString()];b=-1;a&&(b=he(a,c,d,e));return-1<b?a[b]:null};ke=function(a){return Nb(a.g,function(b){for(var c=0;c<b.length;)return!0;return!1})};
he=function(a,b,c,d){for(var e=0;e<a.length;++e){var g=a[e];if(!g.removed&&g.listener==b&&g.capture==!!c&&g.cc==d)return e}return-1};
var le,me,ne,re,te,ue,ve,ye;le="closure_lm_"+(1E6*Math.random()|0);me={};ne=0;_.pe=function(a,b,c,d,e){if(d&&d.once)return _.oe(a,b,c,d,e);if(Array.isArray(b)){for(var g=0;g<b.length;g++)_.pe(a,b[g],c,d,e);return null}c=_.qe(c);return _.ce(a)?a.listen(b,c,_.Jb(d)?!!d.capture:!!d,e):re(a,b,c,!1,d,e)};
re=function(a,b,c,d,e,g){if(!b)throw Error("s");var h=_.Jb(e)?!!e.capture:!!e,k=_.se(a);k||(a[le]=k=new ge(a));c=k.add(b,c,d,h,g);if(c.proxy)return c;d=te();c.proxy=d;d.src=a;d.listener=c;if(a.addEventListener)Zd||(e=h),void 0===e&&(e=!1),a.addEventListener(b.toString(),d,e);else if(a.attachEvent)a.attachEvent(ue(b.toString()),d);else if(a.addListener&&a.removeListener)a.addListener(d);else throw Error("t");ne++;return c};te=function(){var a=ve,b=function(c){return a.call(b.src,b.listener,c)};return b};
_.oe=function(a,b,c,d,e){if(Array.isArray(b)){for(var g=0;g<b.length;g++)_.oe(a,b[g],c,d,e);return null}c=_.qe(c);return _.ce(a)?a.K(b,c,_.Jb(d)?!!d.capture:!!d,e):re(a,b,c,!0,d,e)};_.we=function(a,b,c,d,e){if(Array.isArray(b))for(var g=0;g<b.length;g++)_.we(a,b[g],c,d,e);else d=_.Jb(d)?!!d.capture:!!d,c=_.qe(c),_.ce(a)?a.j.remove(String(b),c,d,e):a&&(a=_.se(a))&&(b=_.je(a,b,c,d,e))&&_.xe(b)};
_.xe=function(a){if("number"!==typeof a&&a&&!a.removed){var b=a.src;if(_.ce(b))ie(b.j,a);else{var c=a.type,d=a.proxy;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent?b.detachEvent(ue(c),d):b.addListener&&b.removeListener&&b.removeListener(d);ne--;(c=_.se(b))?(ie(c,a),0==c.h&&(c.src=null,b[le]=null)):fe(a)}}};ue=function(a){return a in me?me[a]:me[a]="on"+a};ve=function(a,b){if(a.removed)a=!0;else{b=new $d(b,this);var c=a.listener,d=a.cc||a.src;a.Yb&&_.xe(a);a=c.call(d,b)}return a};
_.se=function(a){a=a[le];return a instanceof ge?a:null};ye="__closure_events_fn_"+(1E9*Math.random()>>>0);_.qe=function(a){if("function"===typeof a)return a;a[ye]||(a[ye]=function(b){return a.handleEvent(b)});return a[ye]};Qc(function(a){ve=a(ve)});
_.N=function(){_.x.call(this);this.j=new ge(this);this.fb=this;this.U=null};_.F(_.N,_.x);_.N.prototype[be]=!0;_.N.prototype.removeEventListener=function(a,b,c,d){_.we(this,a,b,c,d)};
_.O=function(a,b){var c,d=a.U;if(d)for(c=[];d;d=d.U)c.push(d);a=a.fb;d=b.type||b;if("string"===typeof b)b=new _.Yd(b,a);else if(b instanceof _.Yd)b.target=b.target||a;else{var e=b;b=new _.Yd(d,a);_.Qb(b,e)}e=!0;if(c)for(var g=c.length-1;!b.j&&0<=g;g--){var h=b.g=c[g];e=h.wb(d,!0,b)&&e}b.j||(h=b.g=a,e=h.wb(d,!0,b)&&e,b.j||(e=h.wb(d,!1,b)&&e));if(c)for(g=0;!b.j&&g<c.length;g++)h=b.g=c[g],e=h.wb(d,!1,b)&&e;return e};
_.N.prototype.F=function(){_.N.X.F.call(this);this.j&&this.j.removeAll(void 0);this.U=null};_.N.prototype.listen=function(a,b,c,d){return this.j.add(String(a),b,!1,c,d)};_.N.prototype.K=function(a,b,c,d){return this.j.add(String(a),b,!0,c,d)};_.N.prototype.wb=function(a,b,c){a=this.j.g[String(a)];if(!a)return!0;a=a.concat();for(var d=!0,e=0;e<a.length;++e){var g=a[e];if(g&&!g.removed&&g.capture==b){var h=g.listener,k=g.cc||g.src;g.Yb&&ie(this.j,g);d=!1!==h.call(k,c)&&d}}return d&&!c.defaultPrevented};
var ze=function(){};ze.prototype.g=null;var Be=function(a){var b;(b=a.g)||(b={},Ae(a)&&(b[0]=!0,b[1]=!0),b=a.g=b);return b};
var Ce,De=function(){};_.F(De,ze);var Ee=function(a){return(a=Ae(a))?new ActiveXObject(a):new XMLHttpRequest},Ae=function(a){if(!a.h&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.h=d}catch(e){}}throw Error("u");}return a.h};Ce=new De;
var Fe=function(a,b){this.h=a[_.p.Symbol.iterator]();this.j=b;this.l=0};Fe.prototype[Symbol.iterator]=function(){return this};Fe.prototype.next=function(){var a=this.h.next();return{value:a.done?void 0:this.j.call(void 0,a.value,this.l++),done:a.done}};var Ge=function(a,b){return new Fe(a,b)};
var He="StopIteration"in _.p?_.p.StopIteration:{message:"StopIteration",stack:""},Ie=function(){};Ie.prototype.next=function(){return Ie.prototype.g.call(this)};Ie.prototype.g=function(){throw He;};Ie.prototype.Ga=function(){return this};
var Ne=function(a){if(a instanceof Je||a instanceof Ke||a instanceof Le)return a;if("function"==typeof a.next)return new Je(function(){return Me(a)});if("function"==typeof a[Symbol.iterator])return new Je(function(){return a[Symbol.iterator]()});if("function"==typeof a.Ga)return new Je(function(){return Me(a.Ga())});throw Error("v");},Me=function(a){if(!(a instanceof Ie))return a;var b=!1;return{next:function(){for(var c;!b;)try{c=a.g();break}catch(d){if(d!==He)throw d;b=!0}return{value:c,done:b}}}},
Je=function(a){this.j=a};Je.prototype.Ga=function(){return new Ke(this.j())};Je.prototype[Symbol.iterator]=function(){return new Le(this.j())};Je.prototype.h=function(){return new Le(this.j())};var Ke=function(a){this.j=a};_.E(Ke,Ie);Ke.prototype.g=function(){var a=this.j.next();if(a.done)throw He;return a.value};Ke.prototype.next=function(){return Ke.prototype.g.call(this)};Ke.prototype[Symbol.iterator]=function(){return new Le(this.j)};Ke.prototype.h=function(){return new Le(this.j)};
var Le=function(a){Je.call(this,function(){return a});this.l=a};_.E(Le,Je);Le.prototype.next=function(){return this.l.next()};
_.Oe=function(a,b){this.h={};this.g=[];this.j=this.size=0;var c=arguments.length;if(1<c){if(c%2)throw Error("n");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a)if(a instanceof _.Oe)for(c=a.sa(),d=0;d<c.length;d++)this.set(c[d],a.get(c[d]));else for(d in a)this.set(d,a[d])};_.f=_.Oe.prototype;_.f.ga=function(){Pe(this);for(var a=[],b=0;b<this.g.length;b++)a.push(this.h[this.g[b]]);return a};_.f.sa=function(){Pe(this);return this.g.concat()};
_.f.has=function(a){return Qe(this.h,a)};_.f.clear=function(){this.h={};this.j=this.size=this.g.length=0};_.f.remove=function(a){Qe(this.h,a)?(delete this.h[a],--this.size,this.j++,this.g.length>2*this.size&&Pe(this),a=!0):a=!1;return a};var Pe=function(a){if(a.size!=a.g.length){for(var b=0,c=0;b<a.g.length;){var d=a.g[b];Qe(a.h,d)&&(a.g[c++]=d);b++}a.g.length=c}if(a.size!=a.g.length){var e={};for(c=b=0;b<a.g.length;)d=a.g[b],Qe(e,d)||(a.g[c++]=d,e[d]=1),b++;a.g.length=c}};_.f=_.Oe.prototype;
_.f.get=function(a,b){return Qe(this.h,a)?this.h[a]:b};_.f.set=function(a,b){Qe(this.h,a)||(this.size+=1,this.g.push(a),this.j++);this.h[a]=b};_.f.forEach=function(a,b){for(var c=this.sa(),d=0;d<c.length;d++){var e=c[d],g=this.get(e);a.call(b,g,e,this)}};_.f.keys=function(){return Ne(this.Ga(!0)).h()};_.f.values=function(){return Ne(this.Ga(!1)).h()};_.f.entries=function(){var a=this;return Ge(this.keys(),function(b){return[b,a.get(b)]})};
_.f.Ga=function(a){Pe(this);var b=0,c=this.j,d=this,e=new Ie;e.g=function(){if(c!=d.j)throw Error("w");if(b>=d.g.length)throw He;var g=d.g[b++];return a?g:d.h[g]};e.next=e.g.bind(e);return e};var Qe=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
var Se,Te;_.Re=function(a){if(a.ga&&"function"==typeof a.ga)return a.ga();if("undefined"!==typeof Map&&a instanceof Map||"undefined"!==typeof Set&&a instanceof Set)return Array.from(a.values());if("string"===typeof a)return a.split("");if(Hb(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}b=[];c=0;for(d in a)b[c++]=a[d];return b};
Se=function(a){if(a.sa&&"function"==typeof a.sa)return a.sa();if(!a.ga||"function"!=typeof a.ga){if("undefined"!==typeof Map&&a instanceof Map)return Array.from(a.keys());if(!("undefined"!==typeof Set&&a instanceof Set)){if(Hb(a)||"string"===typeof a){var b=[];a=a.length;for(var c=0;c<a;c++)b.push(c);return b}b=[];c=0;for(var d in a)b[c++]=d;return b}}};
Te=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);else if(Hb(a)||"string"===typeof a)Array.prototype.forEach.call(a,b,void 0);else for(var c=Se(a),d=_.Re(a),e=d.length,g=0;g<e;g++)b.call(void 0,d[g],c&&c[g],a)};
_.Ue=function(a,b){_.N.call(this);this.h=a||1;this.g=b||_.p;this.l=(0,_.D)(this.Ye,this);this.m=Date.now()};_.F(_.Ue,_.N);_.f=_.Ue.prototype;_.f.Ea=!1;_.f.Ca=null;_.f.setInterval=function(a){this.h=a;this.Ca&&this.Ea?(this.stop(),this.start()):this.Ca&&this.stop()};_.f.Ye=function(){if(this.Ea){var a=Date.now()-this.m;0<a&&a<.8*this.h?this.Ca=this.g.setTimeout(this.l,this.h-a):(this.Ca&&(this.g.clearTimeout(this.Ca),this.Ca=null),_.O(this,"tick"),this.Ea&&(this.stop(),this.start()))}};
_.f.start=function(){this.Ea=!0;this.Ca||(this.Ca=this.g.setTimeout(this.l,this.h),this.m=Date.now())};_.f.stop=function(){this.Ea=!1;this.Ca&&(this.g.clearTimeout(this.Ca),this.Ca=null)};_.f.F=function(){_.Ue.X.F.call(this);this.stop();delete this.g};_.Ve=function(a,b,c){if("function"===typeof a)c&&(a=(0,_.D)(a,c));else if(a&&"function"==typeof a.handleEvent)a=(0,_.D)(a.handleEvent,a);else throw Error("x");return 2147483647<Number(b)?-1:_.p.setTimeout(a,b||0)};_.We=function(a){_.p.clearTimeout(a)};
var Xe=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^\\\\/?#]*)@)?([^\\\\/?#]*?)(?::([0-9]+))?(?=[\\\\/?#]|$))?([^?#]+)?(?:\\?([^#]*))?(?:#([\\s\\S]*))?$"),Ye=function(a,b){if(a){a=a.split("&");for(var c=0;c<a.length;c++){var d=a[c].indexOf("="),e=null;if(0<=d){var g=a[c].substring(0,d);e=a[c].substring(d+1)}else g=a[c];b(g,e?decodeURIComponent(e.replace(/\+/g," ")):"")}}};
var Ze=function(a){_.N.call(this);this.headers=new _.Oe;this.D=a||null;this.h=!1;this.A=this.g=null;this.V="";this.l=this.M=this.m=this.H=!1;this.v=0;this.o=null;this.ja="";this.Z=this.$=!1},$e,af,bf,jf,hf,ef;_.F(Ze,_.N);$e=/^https?$/i;af=["POST","PUT"];bf=[];_.cf=function(a,b,c,d,e,g,h){var k=new Ze;bf.push(k);b&&k.listen("complete",b);k.K("ready",k.ua);g&&(k.v=Math.max(0,g));h&&(k.$=h);k.send(a,c,d,e)};Ze.prototype.ua=function(){this.dispose();_.Fb(bf,this)};
Ze.prototype.send=function(a,b,c,d){if(this.g)throw Error("y`"+this.V+"`"+a);b=b?b.toUpperCase():"GET";this.V=a;this.H=!1;this.h=!0;this.g=this.D?Ee(this.D):Ee(Ce);this.A=this.D?Be(this.D):Be(Ce);this.g.onreadystatechange=(0,_.D)(this.ia,this);try{this.M=!0,this.g.open(b,String(a),!0),this.M=!1}catch(g){df(this);return}a=c||"";var e=new _.Oe(this.headers);d&&Te(d,function(g,h){e.set(h,g)});d=e.sa().find(function(g){return"content-type"==g.toLowerCase()});c=_.p.FormData&&a instanceof _.p.FormData;
!_.Db(af,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(g,h){this.g.setRequestHeader(h,g)},this);this.ja&&(this.g.responseType=this.ja);"withCredentials"in this.g&&this.g.withCredentials!==this.$&&(this.g.withCredentials=this.$);try{ef(this),0<this.v&&((this.Z=ff(this.g))?(this.g.timeout=this.v,this.g.ontimeout=(0,_.D)(this.fa,this)):this.o=_.Ve(this.fa,this.v,this)),this.m=!0,this.g.send(a),this.m=!1}catch(g){df(this)}};
var ff=function(a){return _.$a&&_.yc(9)&&"number"===typeof a.timeout&&void 0!==a.ontimeout};Ze.prototype.fa=function(){"undefined"!=typeof _.qa&&this.g&&(_.O(this,"timeout"),this.abort(8))};var df=function(a){a.h=!1;a.g&&(a.l=!0,a.g.abort(),a.l=!1);gf(a);hf(a)},gf=function(a){a.H||(a.H=!0,_.O(a,"complete"),_.O(a,"error"))};Ze.prototype.abort=function(){this.g&&this.h&&(this.h=!1,this.l=!0,this.g.abort(),this.l=!1,_.O(this,"complete"),_.O(this,"abort"),hf(this))};
Ze.prototype.F=function(){this.g&&(this.h&&(this.h=!1,this.l=!0,this.g.abort(),this.l=!1),hf(this,!0));Ze.X.F.call(this)};Ze.prototype.ia=function(){this.isDisposed()||(this.M||this.m||this.l?jf(this):this.Y())};Ze.prototype.Y=function(){jf(this)};
jf=function(a){if(a.h&&"undefined"!=typeof _.qa&&(!a.A[1]||4!=(a.g?a.g.readyState:0)||2!=a.N()))if(a.m&&4==(a.g?a.g.readyState:0))_.Ve(a.ia,0,a);else if(_.O(a,"readystatechange"),4==(a.g?a.g.readyState:0)){a.h=!1;try{_.kf(a)?(_.O(a,"complete"),_.O(a,"success")):(a.N(),gf(a))}finally{hf(a)}}};hf=function(a,b){if(a.g){ef(a);var c=a.g,d=a.A[0]?_.ta:null;a.g=null;a.A=null;b||_.O(a,"ready");try{c.onreadystatechange=d}catch(e){}}};ef=function(a){a.g&&a.Z&&(a.g.ontimeout=null);a.o&&(_.We(a.o),a.o=null)};
_.kf=function(a){var b=a.N();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}if(!c){if(b=0===b)a=String(a.V).match(Xe)[1]||null,!a&&_.p.self&&_.p.self.location&&(a=_.p.self.location.protocol,a=a.substr(0,a.length-1)),b=!$e.test(a?a.toLowerCase():"");c=b}return c};Ze.prototype.N=function(){try{return 2<(this.g?this.g.readyState:0)?this.g.status:-1}catch(a){return-1}};_.lf=function(a){try{return a.g?a.g.responseText:""}catch(b){return""}};
Qc(function(a){Ze.prototype.Y=a(Ze.prototype.Y)});
var nf;_.z=function(a){_.x.call(this);this.Y=a;this.o={}};_.F(_.z,_.x);var mf=[];_.z.prototype.listen=function(a,b,c,d){Array.isArray(b)||(b&&(mf[0]=b.toString()),b=mf);for(var e=0;e<b.length;e++){var g=_.pe(a,b[e],c||this.handleEvent,d||!1,this.Y||this);if(!g)break;this.o[g.key]=g}return this};_.of=function(a,b,c,d){nf(a,b,c,d,void 0)};nf=function(a,b,c,d,e,g){if(Array.isArray(c))for(var h=0;h<c.length;h++)nf(a,b,c[h],d,e,g);else(b=_.oe(b,c,d||a.handleEvent,e,g||a.Y||a))&&(a.o[b.key]=b)};
_.z.prototype.removeAll=function(){_.Mb(this.o,function(a,b){this.o.hasOwnProperty(b)&&_.xe(a)},this);this.o={}};_.z.prototype.F=function(){_.z.X.F.call(this);this.removeAll()};_.z.prototype.handleEvent=function(){throw Error("z");};
_.pf=function(a){_.I.call(this,a)};_.E(_.pf,_.I);_.pf.messageId="uv_r_hrd";
_.qf=function(a){_.I.call(this,a)};_.E(_.qf,_.I);
var Wb=function(a,b){var c=Array.prototype.slice.call(arguments),d=c.shift();if("undefined"==typeof d)throw Error("A");return d.replace(/%([0\- \+]*)(\d+)?(\.(\d+))?([%sfdiu])/g,function(e,g,h,k,l,m,u,y){if("%"==m)return"%";var C=c.shift();if("undefined"==typeof C)throw Error("B");arguments[0]=C;return rf[m].apply(null,arguments)})},rf={s:function(a,b,c){return isNaN(c)||""==c||a.length>=Number(c)?a:a=-1<b.indexOf("-",0)?a+(0,_.Ta)(" ",Number(c)-a.length):(0,_.Ta)(" ",Number(c)-a.length)+a},f:function(a,
b,c,d,e){d=a.toString();isNaN(e)||""==e||(d=parseFloat(a).toFixed(e));var g=0>Number(a)?"-":0<=b.indexOf("+")?"+":0<=b.indexOf(" ")?" ":"";0<=Number(a)&&(d=g+d);if(isNaN(c)||d.length>=Number(c))return d;d=isNaN(e)?Math.abs(Number(a)).toString():Math.abs(Number(a)).toFixed(e);a=Number(c)-d.length-g.length;return d=0<=b.indexOf("-",0)?g+d+(0,_.Ta)(" ",a):g+(0,_.Ta)(0<=b.indexOf("0",0)?"0":" ",a)+d},d:function(a,b,c,d,e,g,h,k){return rf.f(parseInt(a,10),b,c,d,0,g,h,k)}};rf.i=rf.d;rf.u=rf.d;
var sf=function(a,b){this.g=a;this.h=b};sf.prototype.execute=function(a){this.g&&(this.g.call(this.h||null,a),this.g=this.h=null)};sf.prototype.abort=function(){this.h=this.g=null};Qc(function(a){sf.prototype.execute=a(sf.prototype.execute)});
_.P=function(a,b){var c=c||[];this.j=a;this.h=b||null;this.g=[];this.g=this.g.concat(c)};_.P.prototype.toString=function(){return this.j};
_.uf=function(a){_.I.call(this,a,-1,tf)};_.E(_.uf,_.I);var tf=[2];_.uf.messageId="h_exts";
var wf,xf,yf,Bf,Df,Nf,Ff,Hf,Gf,Kf,If,Cf,Of;_.vf=function(a,b){this.h=this.o=this.m="";this.l=null;this.v=this.g="";this.G=!1;var c;a instanceof _.vf?(this.G=void 0!==b?b:a.G,wf(this,a.m),this.o=a.o,this.h=a.h,xf(this,a.l),this.g=a.g,yf(this,zf(a.j)),_.Af(this,a.v)):a&&(c=String(a).match(Xe))?(this.G=!!b,wf(this,c[1]||"",!0),this.o=Bf(c[2]||""),this.h=Bf(c[3]||"",!0),xf(this,c[4]),this.g=Bf(c[5]||"",!0),yf(this,c[6]||"",!0),_.Af(this,c[7]||"",!0)):(this.G=!!b,this.j=new Cf(null,this.G))};
_.vf.prototype.toString=function(){var a=[],b=this.m;b&&a.push(Df(b,Ff,!0),":");var c=this.h;if(c||"file"==b)a.push("//"),(b=this.o)&&a.push(Df(b,Ff,!0),"@"),a.push(encodeURIComponent(String(c)).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.l,null!=c&&a.push(":",String(c));if(c=this.g)this.h&&"/"!=c.charAt(0)&&a.push("/"),a.push(Df(c,"/"==c.charAt(0)?Gf:Hf,!0));(c=this.j.toString())&&a.push("?",c);(c=this.v)&&a.push("#",Df(c,If));return a.join("")};
_.vf.prototype.resolve=function(a){var b=new _.vf(this),c=!!a.m;c?wf(b,a.m):c=!!a.o;c?b.o=a.o:c=!!a.h;c?b.h=a.h:c=null!=a.l;var d=a.g;if(c)xf(b,a.l);else if(c=!!a.g){if("/"!=d.charAt(0))if(this.h&&!this.g)d="/"+d;else{var e=b.g.lastIndexOf("/");-1!=e&&(d=b.g.substr(0,e+1)+d)}e=d;if(".."==e||"."==e)d="";else if(-1!=e.indexOf("./")||-1!=e.indexOf("/.")){d=_.oc(e,"/");e=e.split("/");for(var g=[],h=0;h<e.length;){var k=e[h++];"."==k?d&&h==e.length&&g.push(""):".."==k?((1<g.length||1==g.length&&""!=g[0])&&
g.pop(),d&&h==e.length&&g.push("")):(g.push(k),d=!0)}d=g.join("/")}else d=e}c?b.g=d:c=""!==a.j.toString();c?yf(b,zf(a.j)):c=!!a.v;c&&_.Af(b,a.v);return b};wf=function(a,b,c){a.m=c?Bf(b,!0):b;a.m&&(a.m=a.m.replace(/:$/,""))};xf=function(a,b){if(b){b=Number(b);if(isNaN(b)||0>b)throw Error("D`"+b);a.l=b}else a.l=null};yf=function(a,b,c){b instanceof Cf?(a.j=b,Jf(a.j,a.G)):(c||(b=Df(b,Kf)),a.j=new Cf(b,a.G))};_.Q=function(a,b,c){a.j.set(b,c)};_.Af=function(a,b,c){a.v=c?Bf(b):b};
_.Lf=function(a){return a instanceof _.vf?new _.vf(a):new _.vf(a,void 0)};_.Mf=function(a,b){a instanceof _.vf||(a=_.Lf(a));b instanceof _.vf||(b=_.Lf(b));return a.resolve(b)};Bf=function(a,b){return a?b?decodeURI(a.replace(/%25/g,"%2525")):decodeURIComponent(a):""};Df=function(a,b,c){return"string"===typeof a?(a=encodeURI(a).replace(b,Nf),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null};Nf=function(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)};Ff=/[#\/\?@]/g;
Hf=/[#\?:]/g;Gf=/[#\?]/g;Kf=/[#\?@]/g;If=/#/g;Cf=function(a,b){this.h=this.g=null;this.j=a||null;this.l=!!b};Of=function(a){a.g||(a.g=new _.Oe,a.h=0,a.j&&Ye(a.j,function(b,c){a.add(decodeURIComponent(b.replace(/\+/g," ")),c)}))};Cf.prototype.add=function(a,b){Of(this);this.j=null;a=Pf(this,a);var c=this.g.get(a);c||this.g.set(a,c=[]);c.push(b);this.h+=1;return this};
Cf.prototype.remove=function(a){Of(this);a=Pf(this,a);return this.g.has(a)?(this.j=null,this.h-=this.g.get(a).length,this.g.remove(a)):!1};Cf.prototype.clear=function(){this.g=this.j=null;this.h=0};var Qf=function(a,b){Of(a);b=Pf(a,b);return a.g.has(b)};_.f=Cf.prototype;_.f.forEach=function(a,b){Of(this);this.g.forEach(function(c,d){c.forEach(function(e){a.call(b,e,d,this)},this)},this)};
_.f.sa=function(){Of(this);for(var a=this.g.ga(),b=this.g.sa(),c=[],d=0;d<b.length;d++)for(var e=a[d],g=0;g<e.length;g++)c.push(b[d]);return c};_.f.ga=function(a){Of(this);var b=[];if("string"===typeof a)Qf(this,a)&&(b=b.concat(this.g.get(Pf(this,a))));else{a=this.g.ga();for(var c=0;c<a.length;c++)b=b.concat(a[c])}return b};_.f.set=function(a,b){Of(this);this.j=null;a=Pf(this,a);Qf(this,a)&&(this.h-=this.g.get(a).length);this.g.set(a,[b]);this.h+=1;return this};
_.f.get=function(a,b){if(!a)return b;a=this.ga(a);return 0<a.length?String(a[0]):b};_.Rf=function(a,b,c){a.remove(b);0<c.length&&(a.j=null,a.g.set(Pf(a,b),_.Gb(c)),a.h+=c.length)};Cf.prototype.toString=function(){if(this.j)return this.j;if(!this.g)return"";for(var a=[],b=this.g.sa(),c=0;c<b.length;c++){var d=b[c],e=encodeURIComponent(String(d));d=this.ga(d);for(var g=0;g<d.length;g++){var h=e;""!==d[g]&&(h+="="+encodeURIComponent(String(d[g])));a.push(h)}}return this.j=a.join("&")};
var zf=function(a){var b=new Cf;b.j=a.j;a.g&&(b.g=new _.Oe(a.g),b.h=a.h);return b},Pf=function(a,b){b=String(b);a.l&&(b=b.toLowerCase());return b},Jf=function(a,b){b&&!a.l&&(Of(a),a.j=null,a.g.forEach(function(c,d){var e=d.toLowerCase();d!=e&&(this.remove(d),_.Rf(this,e,c))},a));a.l=b};
var Sf;Sf=function(a){return(a=a.exec(_.Fa))?a[1]:""};_.Tf=function(){if(_.sb)return Sf(/Firefox\/([0-9.]+)/);if(_.$a||_.ab||_.Za)return _.rb;if(_.wb){if(_.Va()||_.Wa()){var a=Sf(/CriOS\/([0-9.]+)/);if(a)return a}return Sf(/Chrome\/([0-9.]+)/)}if(_.xb&&!_.Va())return Sf(/Version\/([0-9.]+)/);if(_.tb||_.ub){if(a=/Version\/(\S+).*Mobile\/(\S+)/.exec(_.Fa))return a[1]+"."+a[2]}else if(_.vb)return(a=Sf(/Android\s+([0-9.]+)/))?a:Sf(/Version\/([0-9.]+)/);return""}();
_.Uf=function(a){this.g=a||{cookie:""}};_.f=_.Uf.prototype;
_.f.set=function(a,b,c){var d=!1;if("object"===typeof c){var e=c.Lf;d=c.secure||!1;var g=c.domain||void 0;var h=c.path||void 0;var k=c.ye}if(/[;=\s]/.test(a))throw Error("F`"+a);if(/[;\r\n]/.test(b))throw Error("G`"+b);void 0===k&&(k=-1);this.g.cookie=a+"="+b+(g?";domain="+g:"")+(h?";path="+h:"")+(0>k?"":0==k?";expires="+(new Date(1970,1,1)).toUTCString():";expires="+(new Date(Date.now()+1E3*k)).toUTCString())+(d?";secure":"")+(null!=e?";samesite="+e:"")};
_.f.get=function(a,b){for(var c=a+"=",d=(this.g.cookie||"").split(";"),e=0,g;e<d.length;e++){g=(0,_.Aa)(d[e]);if(0==g.lastIndexOf(c,0))return g.substr(c.length);if(g==a)return""}return b};_.f.remove=function(a,b,c){var d=void 0!==this.get(a);this.set(a,"",{ye:0,path:b,domain:c});return d};_.f.sa=function(){return Vf(this).keys};_.f.ga=function(){return Vf(this).values};_.f.clear=function(){for(var a=Vf(this).keys,b=a.length-1;0<=b;b--)this.remove(a[b])};
var Vf=function(a){a=(a.g.cookie||"").split(";");for(var b=[],c=[],d,e,g=0;g<a.length;g++)e=(0,_.Aa)(a[g]),d=e.indexOf("="),-1==d?(b.push(""),c.push(e)):(b.push(e.substring(0,d)),c.push(e.substring(d+1)));return{keys:b,values:c}};
var Wf=function(a,b){_.Yd.call(this,a,b);this.da=b};_.E(Wf,_.Yd);
var Xf=function(a){_.I.call(this,a)};_.E(Xf,_.I);var Yf=function(a,b){return _.H(a,1,b)};
var Zf=function(a){_.I.call(this,a)};_.E(Zf,_.I);var $f=function(a,b){return _.H(a,1,b)},ag=function(a,b){return _.H(a,2,b)},bg=function(a,b){return _.H(a,3,b)};Zf.messageId="capi_md1571";
var Xb=function(){for(var a=10,b=cg,c=b.length,d="";0<a--;)d+=b.charAt(Math.floor(Math.random()*c));return d},cg="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
_.F(_.Yb,_.x);_.Yb.prototype.Sa=function(a,b,c){this.l=a;this.j=b;this.h=c};
_.Yb.prototype.A=function(a){a=a.xa;var b=a.origin;this.j&&this.j!=a.source||"*"!=this.l&&this.l!=b?b=!1:this.h?(b=(new _.vf(b)).h,b=_.pc(b,this.h)?b.length==this.h.length||"."==this.h[0]||"."==b[b.length-1-this.h.length]:!1):b=!0;if(b&&(b=a.data)&&"string"===typeof b&&"["==b[0]){try{var c=JSON.parse(b);if(!Array.isArray(c))return}catch(d){return}if(0!=c.length&&c[0]==Zf.messageId&&(c=new Zf(c),_.B(c,1)==this.o)){b=_.B(c,3);if(!this.g)this.g=b;else if(this.g!=b)return;"*"!=this.l&&this.j||this.Sa(a.origin,
a.source);1==_.B(c,2)?this.send(2):this.v(c,a)}}};_.Yb.prototype.send=function(a,b,c){if(this.g&&this.j){var d=_.Ic(ag($f(bg(b||new Zf,this.o),this.g),a)),e=this.j,g=this.l;_.$a?_.Ve(function(){e.postMessage(d,g)}):c?e.postMessage(d,g,c):e.postMessage(d,g)}};
var dg=function(a,b,c,d){this.j=_.td();this.g=new _.Yb((0,_.D)(this.m,this),c);this.g.Sa("*",a,d);this.g.g=b;this.h=new _.Ue(50);this.h.start();_.pe(this.h,"tick",this.l,!1,this);this.l();_.wd(this.j.promise,this.G,this)};dg.prototype.G=function(){_.t(this.g);_.we(this.h,"tick",this.l,!1,this);_.t(this.h)};dg.prototype.l=function(){this.g.send(1)};dg.prototype.m=function(a,b){2==_.B(a,2)&&this.j.resolve(b.origin)};
_.F(Zb,_.x);Zb.prototype.send=function(a){var b=new Zf;a=_.L(b,4,a);this.g.send(0,a)};Zb.prototype.connect=function(a,b){this.g.Sa(a,b);this.g.send(3)};Zb.prototype.j=function(a){0==_.B(a,2)&&(a=_.K(a,Xf,4),this.h(a))};Zb.prototype.l=_.ta;
var $b=function(a,b,c){_.x.call(this);this.m=a;this.h=this.g=this.j=null;c?(this.h=c.ports[0],eg(this)):(this.g=new _.Yb(_.ta,_.B(b,1)),a=_.B(b,3),this.g.g=a)};_.E($b,_.x);$b.prototype.F=function(){_.x.prototype.F.call(this);this.h&&this.h.close();_.t(this.g)};$b.prototype.l=function(){this.j=new _.z(this);_.A(this,this.j);eg(this)};$b.prototype.send=function(a){this.h.postMessage(a.toJSON())};
$b.prototype.connect=function(a,b){var c=new MessageChannel;this.h=c.port1;eg(this);var d=this.g;this.g=null;c=c.port2;d.Sa(a,b);d.send(4,void 0,[c]);_.t(d)};var eg=function(a){a.h&&a.j&&(a.j.listen(a.h,"message",a.o),a.h.start())};$b.prototype.o=function(a){a=a.xa;try{var b=new Xf(a.data)}catch(c){return}this.m(b)};
var jg,lg;_.fg=function(){_.N.call(this);this.o=null;this.v=!1;this.m=[];this.l=[];_.M(this,this.D,this);this.h=null};_.E(_.fg,_.N);_.fg.prototype.D=function(){for(;this.l.length;)this.l.shift()()};_.hg=function(a){a.D();a.m=[];a.h=new _.Gd;a.l.push((0,_.D)(a.h.cancel,a.h));a.v=!1;_.Nd(a.h.j(),function(b){(ke(this.j)||this.U)&&_.gg(this);this.l.push(_.mc(_.t,b))},a)};_.fg.prototype.sendMessage=function(a){ig(this,Tb(_.Hc(a,!1)))};var ig=function(a,b){if(a.h){var c=Yf(new Xf,b);_.Nd(a.h.j(),function(d){d.send(c)})}};
_.fg.prototype.W=function(){return this};_.fg.prototype.Sa=function(a,b,c){this.g.Sa(a,b,c)};_.kg=function(a,b,c,d){_.hg(a);jg(a,b,c,d).then(function(e){var g=bg($f(new Zf,e.Ze),c);g=ac((0,_.D)(this.A,this),g);g.connect(e.origin,b);this.h.callback(g)},void 0,a)};jg=function(a,b,c,d){var e=Xb();b=(new dg(b,c,e,d)).j.promise;a.l.push((0,_.D)(b.cancel,b));return b.then(function(g){return{Ze:e,origin:g}})};
_.fg.prototype.M=function(a,b){if(3==_.B(a,2)||4==_.B(a,2))_.t(this.g),this.g=null,this.h.callback(ac((0,_.D)(this.A,this),a,b))};_.fg.prototype.A=function(a){this.m.push(a);this.H()};_.fg.prototype.H=function(){for(;lg(this););};lg=function(a){if(a.isDisposed()||!a.v||0==a.m.length)return!1;var b=_.B(a.m.shift(),1);a.o&&ig(a.o,b);_.O(a,new Wf(b[0],b));return!0};_.gg=function(a){a.v||(a.v=!0,a.h&&_.Nd(a.h.j(),function(b){b.l();_.Ve(this.H,0,this)},a))};
_.fg.prototype.listen=function(a,b,c,d){_.gg(this);return _.N.prototype.listen.call(this,a,b,c,d)};_.fg.prototype.K=function(a,b,c,d){_.gg(this);return _.N.prototype.K.call(this,a,b,c,d)};
var mg=function(a){this.h=a;this.l="empty";this.g=null;this.j={}};mg.prototype.getContext=function(){return this.j};mg.prototype.Qa=function(a){this.l=a;return this};mg.prototype.Gb=function(a){this.g=a;return this};mg.prototype.Sc=function(a){this.j=_.Ob(a);return this};
var ng=function(){};
var og=function(){};_.F(og,ng);og.prototype[Symbol.iterator]=function(){return Ne(this.Ga(!0)).h()};og.prototype.clear=function(){var a=Array.from(this);a=_.n(a);for(var b=a.next();!b.done;b=a.next())this.remove(b.value)};
var pg=function(a){this.g=a};_.F(pg,og);_.f=pg.prototype;_.f.isAvailable=function(){if(!this.g)return!1;try{return this.g.setItem("__sak","1"),this.g.removeItem("__sak"),!0}catch(a){return!1}};_.f.set=function(a,b){try{this.g.setItem(a,b)}catch(c){if(0==this.g.length)throw"Storage mechanism: Storage disabled";throw"Storage mechanism: Quota exceeded";}};_.f.get=function(a){a=this.g.getItem(a);if("string"!==typeof a&&null!==a)throw"Storage mechanism: Invalid value was encountered";return a};
_.f.remove=function(a){this.g.removeItem(a)};_.f.Ga=function(a){var b=0,c=this.g,d=new Ie;d.g=function(){if(b>=c.length)throw He;var e=c.key(b++);if(a)return e;e=c.getItem(e);if("string"!==typeof e)throw"Storage mechanism: Invalid value was encountered";return e};d.next=d.g.bind(d);return d};_.f.clear=function(){this.g.clear()};_.f.key=function(a){return this.g.key(a)};
var qg=function(){var a=null;try{a=window.localStorage||null}catch(b){}this.g=a};_.F(qg,pg);
var tg=function(a,b){this.j=a;this.g=[];null===rg&&(rg=null);this.h=null;b&&(this.h=new qg);if(null!=this.h&&this.h.isAvailable()&&(a=this.h.get("__webmonitoring_RateThrottler_history_hourlyRate"),null!=a))try{this.g=JSON.parse(a)||[]}catch(c){}a=!1;Array.isArray(this.g)||(this.g=[],a=!0);for(;this.g.length>this.j;)this.g.shift(),a=!0;a&&sg(this)},sg=function(a){if(null!=a.h&&a.h.isAvailable())try{a.h.set("__webmonitoring_RateThrottler_history_hourlyRate",_.Td(a.g))}catch(b){}},rg=null;
_.F(bc,_.x);bc.prototype.setEnabled=function(a){this.m=a};
var ug=function(a){bc.call(this,a);this.K=100;this.A={};this.ma=null;this.j="";this.D=!0;this.o=10;this.h=null;this.l=!1};_.E(ug,bc);_.f=ug.prototype;_.f.Bd=function(a){this.D=a;return this};_.f.We=function(a){this.o=Math.min(a,100);return this};_.f.zd=function(a){this.K=a;return this};_.f.ad=function(a,b){this.A[a]=b;return this};_.f.yd=function(a){this.ma=a;return this};_.f.Ve=function(a){this.j=a;return this};
_.f.enable=function(){if(this.m)return!1;this.v=window.onerror;window.onerror=this.Le.bind(this);this.setEnabled(!0);return!0};
_.f.vd=function(a,b,c,d,e,g){g=void 0===g?new Map:g;var h=_.Lf(window.location.href);a=null!=e&&null!=e.message?e.message:a;var k;if(k="function"!==typeof this.ma||this.ma(h.g,a,b,c,d,e))if(k=this.l){k=Object.keys(this.A);for(var l=100,m=0;m<k.length;++m){var u=k[m];(new RegExp(u)).test(a)&&(l=this.A[u])}if(k=(100*Math.random()).toFixed(6)>=this.K*l/100?!1:!0){0<=this.o&&null===this.h&&(this.h=new tg(this.o,this.D));if(null===this.h)k=!1;else{a:{k=this.h;l=Date.now();if(k.g.length==k.j)if(k.g[0]<
l-36E5)k.g.shift();else{k=!1;break a}k.g.push(l);sg(k);k=!0}k=!k}k=!k&&this.l}}k&&(e=e||null,b=vg(this,h,a,g,b,c,void 0!==d?d:null),b.prod=this.g.h,b.ver=this.g.l,c=null!==e?_.tc(e.stack):"",b=wg(b),_.qc(a)||(d=c.split("\n"),-1<d[0].indexOf(a)&&(d.splice(0,1),c=d.join("\n"))),xg(this,"https://clients2.google.com/cr/staging_report",b,c),h={product:this.g.h,url:h.g,js_errors_count:"1"},a=_.tc(this.g.g),_.qc(a)||(h.version=a),xg(this,"https://clients2.google.com/cr/staging_perf",wg(h)))};
_.f.Le=function(a,b,c,d,e){this.vd(a,b,c,d,e);null!=this.v&&"function"===typeof this.v&&this.v(a,b,c,d,e)};
var vg=function(a,b,c,d,e,g,h){var k=_.Ob(a.g.getContext());d.forEach(function(l,m){k[m]=l});k.url=b.g;k.type="JavascriptError";k.error_message=c;k.browser=yg();k.browser_version=_.Tf;k.os=_.uc()?"Chrome OS":_.r("Linux")?"Linux":_.Xa()?"Windows":_.r("Android")?"Android":_.Ua()?"iPhone":_.r("iPad")?"iPad":_.r("iPod")?"iPod":_.Wa()?"Mac":"Unknown";k.os_version=_.vc();b=a.g.g;null!==b&&(k.channel=b);_.qc(a.j)||(k.guid=a.j);null!==e&&(k.src=e);null!==g&&(k.line=g.toString());null!==h&&(k.column=h.toString());
return k},wg=function(a){var b="",c;for(c in a)b+=_.qc(b)?"?":"&",b+=c+"="+encodeURIComponent(a[c]);return b},xg=function(a,b,c,d){d=d||"";var e=_.qc(d)?{}:{"Content-Type":"text/plain"};_.cf(b+c,a.U.bind(a,b),"POST",d,e,6E4,!0)};ug.prototype.U=function(a,b){_.kf(b.target)};var yg=function(){var a="Other";_.Za?a="Opera":_.$a?a="Internet Explorer":_.sb?a="Firefox":_.wb?a="Chrome":_.xb&&(a="Safari");return a};ug.prototype.reportError=ug.prototype.vd;ug.prototype.enable=ug.prototype.enable;
ug.prototype.setClientId=ug.prototype.Ve;ug.prototype.setCallback=ug.prototype.yd;ug.prototype.addPerErrorMessageSampling=ug.prototype.ad;ug.prototype.setGlobalSampling=ug.prototype.zd;ug.prototype.setMaxErrorsPerHour=ug.prototype.We;ug.prototype.setUseLocalStorage=ug.prototype.Bd;
_.F(dc,bc);dc.prototype.yd=function(a){this.ma=a;return this};var zg=[{age:6E4,name:"1m"},{age:15E5,name:"25m"},{age:36E5,name:"1h"},{age:36E6,name:"10h"}];dc.prototype.enable=function(){if(this.m)return!1;if(window.performance&&window.performance.memory){var a=new _.Ue(6E4);_.A(this,a);var b=new _.z(this);_.A(this,b);b.listen(a,"tick",this.j);a.start();this.setEnabled(!0);return!0}return!1};
dc.prototype.j=function(){this.h+=6E4;for(var a="",b=0;b<zg.length;++b)if(this.h==zg[b].age){a=zg[b].name;break}if(""!=a){b=Ag.test(_.Fa)?"":"32_bit_";var c=window.performance.memory;if(c.totalJSHeapSize&&c.usedJSHeapSize){a=[{name:"total_"+b+"js_heap_size_mb_"+a+"_raw",displayName:"Total JS heap (MB)",value:Math.round(c.totalJSHeapSize/1048576)},{name:"used_"+b+"js_heap_size_mb_"+a+"_raw",displayName:"Used JS heap (MB)",value:Math.round(c.usedJSHeapSize/1048576)}];b=_.Lf(window.location.href).g;
c="?product="+encodeURIComponent(this.g.h)+"&url="+encodeURIComponent(b);var d=_.tc(this.g.g);_.qc(d)||(c+="&version="+encodeURIComponent(d));for(d=0;d<a.length;++d)c+="&"+encodeURIComponent(a[d].name)+"="+a[d].value,"function"===typeof this.ma&&this.ma(b,a[d].displayName,a[d].value);_.cf("https://clients2.google.com/cr/staging_perf"+c,Bg,"POST","",null,6E4,!0)}}};var Bg=function(a){_.kf(a.target)},Ag=/(x86_64|Win64)/,cc=null;
var Cg=function(a){_.x.call(this);this.config=new mg(a);this.g={}};_.F(Cg,_.x);_.nc("webmonitoring.Monitoring",Cg);Cg.prototype.Qa=function(a){this.config.Qa(a);return this};Cg.prototype.setVersion=Cg.prototype.Qa;Cg.prototype.Gb=function(a){this.config.Gb(a);return this};Cg.prototype.setChannel=Cg.prototype.Gb;Cg.prototype.Sc=function(a){this.config.Sc(a);return this};Cg.prototype.setContext=Cg.prototype.Sc;Cg.prototype.getContext=function(){return this.config.getContext()};
Cg.prototype.ac=function(){null==this.g[2]&&(this.g[2]=new ug(this.config));return this.g[2]};Cg.prototype.createJsErrorsReporter=Cg.prototype.ac;
var ec=function(a){Cg.call(this,a)};_.E(ec,Cg);ec.prototype.Qa=function(a){return Cg.prototype.Qa.call(this,a)};ec.prototype.Gb=function(a){return Cg.prototype.Gb.call(this,a)};ec.prototype.ac=function(){var a=Cg.prototype.ac.call(this);a.l=!0;return a};
var gc,Eg,Fg,Gg;_.Dg=function(){};
gc=function(a){var b=a.lb,c=function(l){c.X.constructor.call(this,l);var m=this.wa.length;this.g=[];for(var u=0;u<m;++u)this.wa[u].If||(this.g[u]=new this.wa[u](l))};_.F(c,b);for(var d=[];a&&a!==Object;){if(b=a.lb){b.wa&&(Ib(d,b.wa),Lb(d));var e=b.prototype,g;for(g in e)if(e.hasOwnProperty(g)&&"function"===typeof e[g]&&e[g]!==b){var h=!!e[g].ce,k=Eg(g,e,d,h);(h=Fg(g,e,k,h))&&(c.prototype[g]=h)}}a=a===Object?Object:Object.getPrototypeOf?Object.getPrototypeOf(a.prototype).constructor||Object:a.X&&a.X.constructor||
Object}c.prototype.wa=d;return c};Eg=function(a,b,c,d){for(var e=[],g=0;g<c.length&&(c[g].prototype[a]===b[a]||(e.push(g),!d));++g);return e};
Fg=function(a,b,c,d){var e;c.length?e=d?function(g){var h=this.g[c[0]];return h?h[a].apply(this.g[c[0]],arguments):this.wa[c[0]].prototype[a].apply(this,arguments)}:b[a].ee?function(g){a:{var h=Array.prototype.slice.call(arguments,0);for(var k=0;k<c.length;++k){var l=this.g[c[k]];if(l=l?l[a].apply(l,h):this.wa[c[k]].prototype[a].apply(this,h)){h=l;break a}}h=!1}return h}:b[a].de?function(g){a:{var h=Array.prototype.slice.call(arguments,0);for(var k=0;k<c.length;++k){var l=this.g[c[k]];l=l?l[a].apply(l,
h):this.wa[c[k]].prototype[a].apply(this,h);if(null!=l){h=l;break a}}h=void 0}return h}:b[a].sd?function(g){for(var h=Array.prototype.slice.call(arguments,0),k=0;k<c.length;++k){var l=this.g[c[k]];l?l[a].apply(l,h):this.wa[c[k]].prototype[a].apply(this,h)}}:function(g){for(var h=Array.prototype.slice.call(arguments,0),k=[],l=0;l<c.length;++l){var m=this.g[c[l]];k.push(m?m[a].apply(m,h):this.wa[c[l]].prototype[a].apply(this,h))}return k}:d||b[a].ee||b[a].de||b[a].sd?e=null:e=Gg;return e};Gg=function(){return[]};
_.Dg.prototype.Fc=function(a){if(this.g)for(var b=0;b<this.g.length;++b)if(this.g[b]instanceof a)return this.g[b];return null};

}catch(e){_._DumpException(e)}
try{
var cv=function(a){return Array.prototype.concat.apply([],arguments)},dv=function(){},ev=function(a){var b=_.Mf(_.B(a,2),"/webchat/extension-start");_.B(a,5)&&_.Q(b,"e",_.B(a,5));return new _.od(function(c,d){_.cf(b,function(e){_.kf(e.target)||d();try{var g=JSON.parse(_.lf(e.target));c(new _.uf(g))}catch(h){d(h.message)}})})},fv=function(a,b,c){c=void 0===c?!1:c;a=_.J(a,b);return null==a?c:a},gv=function(a,b){_.ud(a,null,b,void 0)},hv=function(a,b){return a.j.get(b)},iv=function(a,b){a.o=b;_.M(a,
function(){this.o=null},a);_.gg(a)},jv=function(a){var b=new _.fg;_.hg(b);b.g=new _.Yb((0,_.D)(b.M,b),a);b.g.Sa("*",void 0,void 0);b.l.push(_.mc(_.t,b.g));return b},kv=function(a){(a?a:function(){}).ce=!0},lv=function(a){this.g=a;_.$a||(delete this.g.lpu,delete this.g.ppu)},mv=function(a,b){var c={};c.cn=Math.floor(2147483648*Math.random()).toString(36);c.tp=1;c.ifrid=b;c.pu=a;return new lv(c)},nv=["cn","tp"];_.nc("GTalk_IFrameChannelConfig.build",mv);
_.F(dv,_.Dg);dv.prototype.h=function(a){return a};kv(dv.prototype.h);dv.prototype.j=function(){return!0};kv(dv.prototype.j);
var ov=function(a){_.I.call(this,a)};_.E(ov,_.I);
var pv=function(a,b){var c=new ov;b=_.H(c,1,b);return _.H(b,2,a)},qv=pv("?",0),rv=pv("q",1),sv=pv("<",2),tv=pv(">",3),uv=pv("~",4),vv=pv("s",5),wv={gf:qv,rf:rv,jf:sv,kf:tv,hf:uv,sf:vv};
var xv=function(a){_.I.call(this,a)};_.E(xv,_.I);xv.messageId="ci:ec";
var yv=function(a){_.I.call(this,a)};_.E(yv,_.I);var zv=function(a,b){_.H(a,3,b)},Av=function(a,b){_.H(a,4,b)},Bv=function(a,b){_.H(a,11,b)},Cv=function(a){_.I.call(this,a)};_.E(Cv,_.I);var Dv=function(a){_.I.call(this,a)};_.E(Dv,_.I);var Ev=function(a){_.I.call(this,a)};_.E(Ev,_.I);var Fv=function(a){_.I.call(this,a)};_.E(Fv,_.I);yv.messageId="h_cc";
var Gv=function(a,b){_.ic(this);var c=this.vb.h(a.clientBaseUrl||"https://talkgadget.google.com/talkgadget/");if(_.oc(c,"https://talkgadget.google.com/talkgadget/")){var d=(new _.Uf(window.document)).get("WCSDBG","");d=d.split(";")[0];d=d.split("|")[0];var e=["plus.google.com"],g=RegExp("^[-_a-zA-Z0-9\\.]+\\.talkgadget\\.google\\.com$");0<d.length&&!_.Db(e,d)&&g.test(d)&&(c=_.Lf(c),c=_.Lf("https://"+d+c.g).toString())}this.j=c;this.l=b||new xv;a.notificationsOnly&&_.H(this.l,1,!0);this.h="0";null!=
a.authUser?this.h=a.authUser:(b=hv(new _.vf(window.location.href),"authuser"),null!=b&&(this.h=b));this.v=a.clientUrl||"notifierclient";b=hv(_.Lf(this.v),"authuser");null!=b&&(this.h=b);this.tc=a.propertyName||"Google Talk";this.ha=a.cssUrl;this.locale=a.locale;this.G=a.debug;this.Wb=a.userJid;this.ib=a.uiVersion;this.ue=null!=a.rosterExpanded?a.rosterExpanded:!0;this.fa=a.hostLogMinValue;this.gb=a.hideChat;this.Ec=a.refresh;this.V=a.hideProfileCard;this.$=a.hideStatusMsgs;this.Z=a.hideRosterOptions;
this.Y=a.hideRecentConversations;this.M=a.hideOTR;this.xc=a.hostServerMessageCallback||!1;this.ja=a.isCentralRoster;this.Cc=a.isFullFrame||!1;this.re=a.rosterClass||"talk_roster";this.ve=a.rosterId||"talk_roster";this.g="gtn-roster-iframe-id";a.rosterFrameId&&a.rosterFrameId.match(/[\w-]/)&&(this.g=a.rosterFrameId);a.rosterIframeIdB&&a.rosterIframeIdB.match(/[\w-]/);this.fb=a.parentToken;void 0!==a.isRtl||_.za.test(this.locale);this.position=a.position||"l";if(!a.keyboardShortcuts){b=[];for(var h in wv)b.push(wv[h].toJSON())}this.D=
a.entityId;this.jb=a.useQuasarPanels||!1;this.silent=a.silent||!1;this.zc=a.ignoreCentralRoster||!1;this.Jc=a.lazy||!1;this.wc=a.handleProfileLinks||!1;this.ia=a.hostSettings;this.o=a.screen;this.K=a.docsConfig;this.Gc=a.jsmode;this.Ra=a.moleWidth;this.Fa=a.moleHeight;this.ua=a.minimizedMoleHeight||36;this.we=a.derp;this.hb=window.location.protocol+"//"+window.location.host;this.m="";this.H=a.optOutAllowed;this.U=a.legacyTalkSignedIn;this.Xb=a.useSpareMole;this.A=a.conversationId};dv.X||_.F(dv,_.Dg);
Gv.lb=dv;new _.P("du37De");
var Iv=function(a){var b={},c=_.Jc(a,1,"hangouts.google.com"),d="";0>c.indexOf("://")&&(d="https://",0<=c.indexOf(":")&&23!=_.B(a,2)&&27!=_.B(a,2)&&(d="http://"));b.clientBaseUrl=d+c+"/webchat/u/"+_.Jc(a,8,"0")+"/";b.clientUrl="load";b.authUser=_.Jc(a,8,"0");b.propertyName=Hv(_.B(a,2));b.locale=_.B(a,4);b.hideProfileCard=!0;b.parentToken=_.B(a,3);b.isRtl=fv(a,6,!1);b.lazy=fv(a,7,!1);b.entityId=_.B(a,9);b.hostSettings=_.B(a,5);b.jsmode=_.B(a,11);b.isFullFrame=fv(a,13,!1);b.rosterId=_.Jc(a,12,"talk_roster");
b.rosterIframeId=_.Jc(a,12,"talk_roster");b.rosterIframeIdB=_.Jc(a,15,"gtn-roster-iframe-id-b");b.derp=!!fv(a,16,!1);c=_.K(a,Fv,14);null!=c&&(b.isCentralRoster=fv(c,1,!1),b.useQuasarPanels=fv(c,2,!1));c=_.K(a,Cv,10);null!=c&&(b.moleManagerLeftMargin=_.B(c,1),b.moleManagerMiddleMargin=_.B(c,2),b.moleManagerRightMargin=_.B(c,3),b.moleManagerNoMoleAreaMargin=_.B(c,4),b.moleManagerBoundingElementId=_.B(c,5),b.moleWidth=_.B(c,6),b.moleHeight=_.B(c,7),b.minimizedMoleHeight=_.B(c,8));c=_.K(a,Dv,18);null!=
c&&(b.optOutAllowed=fv(c,1,!0),d=_.K(c,Ev,3),null!=d&&(b.legacyTalkSignedIn=fv(d,1,!0)),c=_.J(c,4),null!=c&&(b.useSpareMole=c));b.uiVersion=2;b.hideStatusMsgs=!0;b.hideRecentConversations=!0;c=new xv;c=_.H(c,2,!0);c=_.H(c,1,!0);c=_.H(c,3,!1);b.endpointConfig=c;b.ignoreAutomatedRoster=fv(a,17,!1);b.conversationId=_.B(a,19);return b},Hv=function(a){switch(a){case 1:return"homepage";case 4:return"Google Translator Toolkit";case 5:return"Google Sites";case 6:return"customersupport";case 9:return"present";
case 15:return"hangout";case 18:return"gmail";case 20:return"docs";case 24:return"docs_hangout";case 22:return"hangout_lite";case 23:return"aChromeExtension";case 27:return"ChromeApp";case 36:return"StartPage"}},Jv=function(a,b){if(-1!=a.indexOf("talkgadget.")){var c=_.Lf(a),d=c.g;if(0<=d.indexOf("/u/"))return a;a=d.lastIndexOf("_/");if(0>a||a!=d.length-2)d+="_/";c.g="/u/"+b+d;return c.toString()}return a};
var Kv=function(a,b,c,d,e){_.x.call(this);this.g=a;this.h=d||window.document;this.j=new _.z(this);_.A(this,this.j);var g=_.Fa;d=new _.vf(a.j+a.v);fv(a.l,2,!1)||(_.Q(d,"ts","0"),_.Q(d,"re",a.ue),_.Q(d,"ref",a.Ec));_.Q(d,"client","sm");_.Q(d,"prop",a.tc);_.Q(d,"nav","true");_.Q(d,"fid",a.g);a.G&&_.Q(d,"debug",a.G);_.Q(d,"os",_.eb);_.Q(d,"stime",c);a.gb&&_.Q(d,"hc",a.gb);for(c=0;c<nv.length;++c);b=_.Td(b.g);_.Q(d,"xpc",b);_.Q(d,"ec",_.Td(a.l.toJSON()));a.o&&_.Q(d,"screen",a.o);-1!=g.indexOf("MSIE")&&
_.Q(d,"ua",g);a.fb&&_.Q(d,"pvt",a.fb);a.xc&&_.Q(d,"hsmc","true");void 0!==a.fa&&_.Q(d,"logl",a.fa);b=window.location.href;0>b.indexOf("?rel=1")&&(b=b.split("?"),b[1]=1==b.length?"rel=1":["rel=1&",b[1]].join(""),_.Q(d,"href",b.join("?")));b=new _.vf(window.location.href);"false"==hv(b,"uacheck")&&_.Q(d,"uacheck",!1);(g=a.Gc)&&_.Q(d,"jsmode",g);(g=hv(b,"cssmode"))&&_.Q(d,"cssmode",g);(g=hv(b,"convid"))&&_.Q(d,"convid",g);if(g=b.j.ga("convp"))Array.isArray(g)||(g=[String(g)]),_.Rf(d.j,"convp",g);(g=
hv(b,"smexp"))&&_.Q(d,"smexp",g);g=b.j.ga("mods");a.Jc&&g.push("lazy");e&&(g=cv(g,e));0<g.length&&_.Q(d,"mods",g.join(","));if(!a.j||0>a.j.indexOf("/u/"))(e=hv(b,"authuser"))?_.Q(d,"authuser",e):null!=a.h&&_.Q(d,"authuser",a.h);e=hv(b,"eid");_.qc(_.tc(e))||_.Q(d,"eid",e);_.qc(_.tc(this.g.D))||_.Q(d,"eid",this.g.D);null!=this.g.position&&_.Q(d,"pos",this.g.position);void 0!==a.ib&&_.Q(d,"uiv",this.g.ib);a.ha&&_.Q(d,"css",a.ha);e=a.locale||hv(b,"hl");null!=e&&_.Q(d,"hl",e);void 0!==a.Wb&&_.Q(d,"uj",
a.Wb);null!=a.V&&_.Q(d,"hpc",a.V);null!=a.$&&_.Q(d,"hsm",a.$);null!=a.Z&&_.Q(d,"hro",a.Z);null!=a.Y&&_.Q(d,"hrc",a.Y);null!=a.M&&_.Q(d,"hotr",a.M);null!=a.ja&&_.Q(d,"pop",a.ja);_.Q(d,"pal","1");null!=a.jb&&_.Q(d,"uqp",a.jb);null!=a.H&&_.Q(d,"gooa",a.H);null!=a.U&&_.Q(d,"gltsi",a.U);null!=a.Xb&&_.Q(d,"gusm",a.Xb);null!=a.silent&&_.Q(d,"sl",a.silent);a.zc&&_.Q(d,"icr","1");a.wc&&_.Q(d,"hpl","1");a.ia&&_.Q(d,"hs",a.ia);a.K&&_.Q(d,"dc",_.Td(a.K.toJSON()));null!=a.Ra&&_.Q(d,"molew",a.Ra);null!=a.Fa&&_.Q(d,
"moleh",a.Fa);null!=a.ua&&_.Q(d,"mmoleh",a.ua);a.we&&_.Q(d,"derp","1");a.m&&_.Q(d,"fcho",a.m);null!=a.hb&&_.Q(d,"two",a.hb);null!=a.A&&_.Q(d,"convid",a.A);_.Q(d,"host","1");_.Q(d,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^Date.now()).toString(36));this.l=d.toString()};_.E(Kv,_.x);Kv.prototype.install=function(a,b){Lv(this,a,b,_.ta)};
var Lv=function(a,b,c,d){var e=a.h.getElementById(b);e||(e=a.h.createElement("div"),e.id=b,e.className=a.g.re,a.h.body.appendChild(e));a=(0,_.D)(function(){var g="";this.g.Cc||(g="height:400px");var h=_.Zc(new _.Yc(this.h),"IFRAME");_.Uc(h,{id:this.g.g,name:this.g.g,"class":"talk_iframe",frameborder:"0",style:g,"aria-hidden":"true",allow:"microphone *; autoplay *; microphone"});_.Sc("talk_loading_msg",e)||_.Xc(e);e.appendChild(h);var k=this.h.getElementById(this.g.g);_.of(this.j,k,["load","error"],
function(l){k.contentWindow.postMessage("AllowFrame: Chat","*");d(l)});k.src=this.l.toString();c()},a);window.setTimeout(a,0)};
var Nv=function(){_.z.call(this);var a=this;_.v("Starting ...");this.listen(window,"unload",this.dispose);this.h=new _.qf(JSON.parse(decodeURI(location.hash.substr(1))));this.g=jv(_.B(this.h,1));_.A(this,this.g);this.j=new _.fg;_.A(this,this.j);gv(ev(this.h).then(function(b){return Mv(a,b)}),function(b){_.v("Failed to start : %s.",b||"")})},Ov;_.E(Nv,_.z);
var Mv=function(a,b){if(!a.isDisposed()&&(a.g.sendMessage(b),_.B(b,1))){var c=new yv,d=_.Lf(_.B(a.h,2)),e=d.h;null!=d.l&&(e+=":"+d.l);_.H(c,1,e);_.H(c,2,27);_.H(c,13,!0);_.H(c,17,!0);zv(c,_.B(b,1));Bv(c,_.B(a.h,4));Av(c,_.B(a.h,3)||"en");b=Iv(c);var g=new Gv(b,b.endpointConfig);g.j=Jv(g.j,g.h);g.m=location.origin;g.g="gtn-roster-iframe-id-q";b=mv(g.j,g.g);b=new Kv(g,b,Date.now(),window.document);_.A(a,b);Lv(b,g.ve,function(){},function(){_.kg(a.j,document.getElementById(g.g).contentWindow,"31ACFC0_",
"google.com");iv(a.j,a.g);iv(a.g,a.j);a.g.sendMessage(new _.pf)})}};_.nc("default_host._DumpException",function(a){return console.error(a.stack)});_.fc();if(!Ov||Ov.isDisposed())Ov=new Nv;

}catch(e){_._DumpException(e)}
}).call(this,this.default_host);
// Google Inc.
